'use strict';

/* ================================================================
   the site's content, extracted from index.html so it can be edited
   without wading through the comb machinery. loaded as a plain
   script before the main one - everything here is a global const
   the comb script reads. no build step, as ever.

   keys are cell paths from the origin comb (q,r axial coords joined
   by |). three item shapes:
     { section: true, glyph, title }              a labelled room
     { glyph, title, act, href, blurb }           a link plaque
     { note: '…', glyph }                         a prose note
   ================================================================ */

const SEED_CONTENT = {
  // ---- the centre cell is me: a whole about-room, not a link ----
  '0,0':  { section: true, glyph: '🐝', title: 'about me 💅' },
  '0,0|1,0':  { note: 'i live in dorset, near the coast. i’ve been a software engineer for a while now; three kids.', glyph: '🌳' },
  '0,0|0,1':  { note: 'this whole page is one infinite honeycomb. dive into any dark cell, or zoom out forever - there is no top.', glyph: '⬡' },
  '0,0|-1,1': { note: 'the site is hand-written html - no build step, no framework, no dependencies. every previous version of it lives in the museum.',
                glyph: '🏛', href: '/museum/', act: 'visit the museum' },
  '0,0|-1,0': { note: 'seven chickens patrol the garden. i’m assured they are mine.', glyph: '🐔' },
  '0,0|0,-1': { glyph: '✉', title: 'say hello', act: 'email', href: 'mailto:wmmclarke@gmail.com',
                blurb: 'wmmclarke@gmail.com' },
  '0,0|2,-1': { glyph: '💼', title: 'linkedin', act: 'visit', href: 'https://www.linkedin.com/in/wmmclarke/',
                blurb: 'the professional mask.' },
  '0,0|-2,1': { glyph: '📡', title: 'rss', act: 'subscribe', href: '/index.xml',
                blurb: 'the writing, as a feed.' },
  '0,0|-1,-1': { glyph: '📈', title: 'stats', act: 'view', href: '/stats.html',
                 blurb: 'numbers about this site.' },
  '0,0|2,-2': { glyph: '⚙', title: 'sourcehut', act: 'visit', href: 'https://git.sr.ht/~will-clarke',
                blurb: 'a mirror; some older code lives here too.' },
  '0,0|1,-2': { note: 'the kids are not in these hexagons. some things you don’t put on the internet.', glyph: '🌱' },
  // ---- code: github and the projects that live there ----
  '0,0|2,0': { section: true, glyph: '🐙', title: 'code' },
  '0,0|2,0|1,0': { glyph: '🐙', title: 'github', act: 'visit', href: 'https://github.com/will-clarke',
                   blurb: 'most of the code. quality varies.' },
  '0,0|2,0|0,1': { glyph: '🦠', title: 'evolution', accent: '#9fdc6a', act: 'watch', href: '/video/evolution.webm',
                   blurb: 'an artificial-life sandbox with no fitness function: things survive because they survive. runs on the shed gpu. the clip probes one creature’s brain mid-swarm.' },
  '0,0|2,0|-1,1': { glyph: '🥔', title: 't8r8r', act: 'visit', href: 'https://t8r8r.fly.dev',
                    blurb: 'potato elo: rate potatoes against each other. the joke is the product, and the product is finished.' },
  '0,0|2,0|-1,0': { glyph: '👾', title: 'chip8', act: 'the code', href: 'https://github.com/will-clarke/chip8',
                    blurb: 'a chip-8 emulator in c, with 36 real roms.' },
  '0,0|2,0|0,-1': { glyph: '🔡', title: 'crossword', act: 'the code', href: 'https://github.com/will-clarke/Crossword',
                    blurb: 'a crossword generator. the dictionary was the easy part. everything was the easy part except finishing.' },
  '0,0|2,0|1,-1': { glyph: '🐍', title: 'snake, in haskell', act: 'the code', href: 'https://github.com/will-clarke/snake-haskell',
                    blurb: 'snake with flags for board size and ascii style. it works fine. that was never the point.' },
  '0,0|2,0|2,-1': { glyph: '📄', title: 'ssssg', act: 'the code', href: 'https://github.com/will-clarke/super-simple-static-site-generator',
                    blurb: 'a static site generator in shell, four s’s. built instead of writing anything to put on a site.' },
  '0,0|2,0|-2,1': { glyph: '🔗', title: 'url shortener', act: 'the code', href: 'https://github.com/will-clarke/url-shortener-golang',
                    blurb: '“slightly over-engineered” by its own readme, for a problem i did not have.' },
  '0,0|2,0|1,1': { glyph: '🕹', title: 'hah', act: 'the code', href: 'https://github.com/will-clarke/hah',
                   blurb: 'a rust arcade game. get past 20,000 points. nobody has, the author included.' },
  // ---- a decade of employers, one hex each ----
  '0,0|1,1': { section: true, glyph: '💼', title: 'the day jobs' },
  '0,0|1,1|1,0':  { note: 'now: blacklane. dispatching - matching rides to chauffeurs, in every timezone at once.', glyph: '🚘' },
  '0,0|1,1|0,1':  { note: 'infosum (2022): privacy maths in go. i mostly remember arguing about api boundaries, slowly, and winning, slowly.', glyph: '🔒' },
  '0,0|1,1|-1,1': { note: 'river island (2020-2022): engineer, then tech lead. we plugged a new warehouse into the business.', glyph: '👕' },
  '0,0|1,1|-1,0': { note: 'ratio (2019-2020): automated a daily reporting grind until it stopped existing. nobody has missed it.', glyph: '📊' },
  '0,0|1,1|0,-1': { note: 'deliveroo (2016-2019): built the tracker people watched their dinner on. also said words at gophercon, once.',
                    glyph: '🛵', href: 'https://www.youtube.com/watch?v=OFM4G0wr8bc', act: 'watch the words' },
  '0,0|1,1|1,-1': { note: 'snaptrip (2014-2016): scrappy holiday-cottage startup. i got stuck in everywhere.', glyph: '🏖' },
  '0,0|1,1|2,-1': { note: 'forward3d (2012-2014): hired as a data analyst; taught myself ruby and quietly automated most of my own job.', glyph: '🤖' },
  '0,0|1,1|-2,1': { note: 'before any of that: a masters in anthropology & archaeology at durham. the trowel-to-keyboard pipeline.', glyph: '🏺' },
  '0,0|1,1|2,-2': { note: 'in 2014 this cv was a pure ruby script. it got weirder from there.',
                    glyph: '💎', href: '/posts/2014-10-12--my-cv...-in-pure-ruby.html', inline: true, act: 'read the post' },
  // ---- interests: the deepest branch on the site, on purpose ----
  '0,0|1,-1': { section: true, glyph: '🧭', title: 'interests' },
  '0,0|1,-1|0,-1': { note: 'outside: walks, the garden, cycling, squash when the knee agrees. dorset does most of the heavy lifting.', glyph: '🥾' },
  '0,0|1,-1|1,1': { note: 'recurring themes: recursion, emergence, geometry - simple rules making complicated things. most of the games here are one of those in disguise.', glyph: '🌀' },
  // films (the canon is filled from FILMS below)
  '0,0|1,-1|1,0': { section: true, glyph: '🎬', title: 'films' },
  '0,0|1,-1|1,0|1,0': { note: 'ghibli with the kids, thrillers after their bedtime, and anything old enough to have earned a second run in a proper cinema.', glyph: '🍿' },
  '0,0|1,-1|1,0|0,1': { note: 'the screening scraper lives at the top level of the comb now - one of the few things here that is actually alive.',
                        glyph: '🎞', href: 'https://classiccult.pages.dev/', act: 'visit' },
  '0,0|1,-1|1,0|-1,0': { section: true, glyph: '🏆', title: 'the canon' },
  // books + games-i-play are filled from BOOKS / PLAYED below
  '0,0|1,-1|0,1': { section: true, glyph: '📚', title: 'books' },
  '0,0|1,-1|-1,0': { section: true, glyph: '🎮', title: 'games i play' },
  // listening
  '0,0|1,-1|-1,1': { section: true, glyph: '🎧', title: 'listening' },
  '0,0|1,-1|-1,1|1,0':  { note: 'mostly music without words. words are for work.', glyph: '🎧' },
  '0,0|1,-1|-1,1|0,1':  { note: 'we lost the sea, and post-rock generally: twelve minutes of build-up, worth it.', glyph: '🌊' },
  '0,0|1,-1|-1,1|-1,1': { note: 'bach: the passions, and anything with a keyboard. the model in the shed learned from the same well - its piece is at the top level.', glyph: '🎼' },
  '0,0|1,-1|-1,1|-1,0': { note: 'the tiger lillies: falsetto, accordion, and subject matter unsuitable for the school run.', glyph: '🎪' },
  '0,0|1,-1|-1,1|0,-1': { note: 'carbon based lifeforms and jean-michel jarre for the focus hours. oxygène 2, specifically.', glyph: '🌌' },
  '0,0|1,-1|-1,1|1,-1': { note: 'nicholas britell and ramin djawadi: television scores are where the composers went.', glyph: '📺' },
  '0,0|1,-1|-1,1|2,-1': { note: 'the zombies, “a rose for emily”. the sixties knew things.', glyph: '🌹' },
  '0,0|1,-1|-1,1|-2,1': { note: 'also: chopin, elo, supertramp, muse, queen, zeppelin, the beatles... and hamilton. a broad shelf, and i’m not embarrassed by any of it. well. one of them.', glyph: '🗄' },
  '0,0|1,-1|-1,1|-1,-1': { note: 'there is nearly always a piano going somewhere in the house. not always well, but going.', glyph: '🎹' },
  // ---- short stories (buried on purpose) - filled from stories.json below ----
  '0,0|1,-1|1,-1': { section: true, glyph: '📖', title: 'short stories' },
  '0,0|1,-1|1,-1|0,-1': { note: 'fiction, from before i knew better. sci-fi mostly, and all quietly worried that none of this is real. the finished ones are through here; the rest are on the open shelf, unfixed.', glyph: '📖' },
  '0,0|1,-1|1,-1|1,0': { section: true, glyph: '📖', title: 'finished' },
  '0,0|1,-1|1,-1|-1,0': { section: true, glyph: '✍', title: 'unfinished' },
  '1,0':  { section: true, glyph: '🕹', title: 'games' },
  '-1,1': { section: true, glyph: '✍', title: 'tech blog' },
  '0,1':  { section: true, glyph: '📐', title: 'draggable maths' },
  '-1,0': { glyph: '🍽', title: 'culprit · food tracker', accent: '#7fe0a0',
            blurb: 'a food & symptom tracker: photograph meals, log symptoms, and let the correlations do the rest. image recognition runs locally on the home server - nothing leaves the house.' },
  // ---- best-of, promoted out of their rooms to the top level ----
  '2,0':  { glyph: '🌀', title: 'recurr · fractal game', act: 'play', href: '/games/recurr/', accent: '#ff7ac2',
            blurb: 'a mark made of itself: every cell is the whole mark, smaller. match the fractal in par.' },
  '1,-1': { glyph: '💎', title: 'polyhedra playground', act: 'play', href: '/games/polyhedra/', accent: '#8affd4',
            blurb: 'dual, truncate, gyro: conway operators on spinning solids. more soothing than it has any right to be.' },
  '2,-1': { glyph: '💧', title: 'painting game', act: 'play', href: '/games/drip/', accent: '#e455ff',
            blurb: 'slide the machines, drop the paint, match the vial. gravity does most of the work.' },
  '0,2':  { glyph: '△', title: 'choose two', act: 'visit', href: '/choosetwo/',
            blurb: 'trilemmas as svg triangles - pick any two: cap theorem, zooko, career / family / hobbies, and more.' },
  '0,-2': { glyph: '🎼', title: 'ai music', act: 'listen', audio: '/audio/bach.mp3', accent: '#c9a2ff',
            blurb: 'a keyboard piece from a model trained in the shed. nobody wrote it; it came out sounding like bach anyway. tap to play.' },
  '2,-2': { glyph: '🎬', title: 'classiccult · film finder', act: 'visit', href: 'https://classiccult.pages.dev/', accent: '#ffd166',
            blurb: 'every classic & cult screening in london, scraped nightly onto one page. no backend, nothing to pay for. i moved to dorset shortly after finishing it.' },
  '1,-2': { note: 'welcome to my hexagon!', glyph: '👋' },
  // ---- the workshop ----
  '-1,-1': { section: true, glyph: '🪓', title: 'the workshop' },
  '-1,-1|1,0':  { note: 'no central heating. the house runs on logs; the logs run on me. winter is a supply chain and i am most of it.', glyph: '🔥' },
  '-1,-1|0,1':  { note: 'ambitions of proper woodworking - steps, tables, one day a log cabin. current verified output: kindling.', glyph: '🪵' },
  '-1,-1|0,-1': { note: 'raspberry pis in various states of employment around the house. the more ambitious electronics stay on the someday shelf, where they’re safe.', glyph: '🔌' },
  '-1,-1|1,1':  { note: 'there is a rock tumbler running in the shed. it will bore me eventually; until then the house hums and produces shiny pebbles nobody asked for.', glyph: '🪨' },
  '-1,-1|-1,0': { section: true, glyph: '🖨', title: '3d printing' },
  '-1,-1|-1,0|1,0':  { note: 'a voron 2.4, built from a kit. a printer whose first job was printing parts for itself, which tells you everything about this hobby.', glyph: '🖨' },
  '-1,-1|-1,0|-1,1': { note: 'occasionally the polyhedra escape the browser and become plastic. a dual of a cube looks better on a shelf than you’d think.',
                       glyph: '💠', href: '/games/polyhedra/', act: 'make one' },
  '-1,-1|-1,0|-1,0': { note: 'spaghetti happens. every printer owner has the photo. mine is not special.', glyph: '🍝' },
  '-1,-1|1,-1': { section: true, glyph: '💭', title: 'the someday shelf' },
  '-1,-1|1,-1|1,0': { note: 'a queue of 3d-printing and electronics ideas, each one fully planned and none started. the queue is the hobby.', glyph: '📋' },
  '-1,-1|1,-1|0,1': { note: 'every idea arrives fully formed, joins the queue, and waits. some have waited years. they’re very patient.', glyph: '⏳' },
  '-1,-1|1,-1|-1,1': { note: 'an e-ink dashboard for the hallway: weather, the calendar, whose turn it is. fully specified, still on paper.', glyph: '🖼' },
  '-1,-1|1,-1|-1,0': { note: 'a keyboard, printed and hand-wired from scratch. i hold strong opinions about switches and have nothing to show for them.', glyph: '⌨' },
  '-1,-1|1,-1|0,-1': { note: 'a clip-together logic kit for the kids: start at a nand gate, end somewhere that feels like magic. the plan is lovely.', glyph: '🔲' },
  '-1,-1|1,-1|1,-1': { note: 'build a computer up from something close to sand: gates, a bus, a clock. nand2tetris, but with a soldering iron and no deadline.', glyph: '🖥' },
  // ---- the shed: the home server, filed in the workshop where it belongs ----
  '-1,-1|-1,1': { section: true, glyph: '🖥', title: 'the shed' },
  '-1,-1|-1,1|0,1':  { note: 'the server lives in an actual shed: a single ryzen box with an rtx 3090 and a stack of disks that is never quite big enough.', glyph: '🖥' },
  '-1,-1|-1,1|-1,1': { note: 'k3s runs the show: frigate watching the garden, immich hoarding photos, jellyfin serving films.', glyph: '☸' },
  '-1,-1|-1,1|-1,0': { note: 'editors: emacs → nvim → helix. currently helix. ask me again next year.', glyph: '⌨' },
  '-1,-1|-1,1|0,-1': { note: 'everything is cattle, except the shed server, which is a beloved pet.', glyph: '🐄' },
  '-1,-1|-1,1|1,0':  { note: 'the whole box is one nix expression. `make rebuild` and the shed comes back from bare metal, grudges intact.', glyph: '❄' },
  '-1,-1|-1,1|1,1':  { note: 'the cloud is just the shed: memos for notes, karakeep for bookmarks, navidrome and audiobookshelf for the ears.', glyph: '☁' },
  '-1,-1|-1,1|2,-1': { note: 'the 3090 moonlights as an ai lab: comfyui, ollama, and an artificial-life sandbox with no fitness function.', glyph: '🧠' },
  '-1,-1|-1,1|-2,1': { note: '*.home.wclarke.net only resolves indoors: adguard dns, one wildcard cert, grafana graphing the lot.', glyph: '🔐' },
  '-1,-1|-1,1|2,0':  { note: 'home assistant runs the house; the ring cameras are smuggled out of their cloud over mqtt. the family dashboard has exactly one user.', glyph: '🏠' },
  '-1,-1|-1,1|-1,-1': { note: 'the long tail: searxng for search, forgejo mirroring git, atuin syncing shell history, ntfy pinging my phone whenever anything sulks.', glyph: '🔎' },
  '-1,-1|-1,1|0,-2': { note: 'borg ships backups out nightly; prometheus and grafana watch everything. the shed complains to my phone before i notice.', glyph: '💾' },
  '-1,-1|-1,1|-1,2': { note: 'forty little comma-prefixed scripts and a hyper key. the dotfiles repo is the real operating system.', glyph: '🔧' },
  '-1,-1|-1,1|-2,2': { note: 'things in the shed die on a rota: a disk, a heatwave, the occasional self-inflicted rebuild. no funerals held.', glyph: '🔥' },
  // ---- philosophical musings (in the about room; armchair successor) ----
  '0,0|-1,2': { section: true, glyph: '💭', title: 'philosophical musings' },
  '0,0|-1,2|1,0':  { note: 'i’m a fully paid-up ai doomer: we should be taking the risks far more seriously. progress is probably inevitable anyway - competition sees to that - so we’d better hope it lands well.', glyph: '🤖' },
  '0,0|-1,2|0,1':  { note: 'consciousness is more common than we think: animals - probably insects too - feel far more than we give them credit for. it stops being a great mystery once you accept it’s just a brain doing the feeling.', glyph: '🐜' },
  '0,0|-1,2|-1,1': { note: 'ai can be conscious, and to some extent probably already is.', glyph: '💡' },
  '0,0|-1,2|-1,0': { note: 'total symmetry acolyte. everything is symmetrical - including, i suspect, our emotions.', glyph: '🦋' },
  '0,0|-1,2|0,-1': { note: 'intelligence is somehow underrated. so is simplicity.', glyph: '💎' },
  '0,0|-1,2|1,-1': { note: 'evolution explains far more about life than we usually admit. it is the ultimate force acting on animals - us included.', glyph: '🧬' },
  '0,0|-1,2|2,0':  { note: 'it’s crazy how simple rules can create complexity.', glyph: '🌱' },
  '0,0|-1,2|1,1':  { note: 'there’s often wisdom in old-fashioned customs and morality.', glyph: '🏺' },
  '0,0|-1,2|0,2':  { note: 'poverty is the natural state; prosperity is the anomaly. we should spend far more time thinking about where prosperity comes from.', glyph: '🌾' },
  '0,0|-1,2|-1,2': { note: 'capitalism is by far the best thing humans have discovered - it has lifted billions out of poverty. economic progress isn’t everything, though.', glyph: '📈' },
  '0,0|-1,2|-2,2': { note: 'we’re evolving ai minds the same way ours were evolved. if they end up feeling things, we’ll have made trillions of them - worth thinking about before, rather than after.', glyph: '🧠' },
  '0,0|-1,2|-1,-1': { note: 'i wonder whether some potential inventions are best left undiscovered.', glyph: '🕳' },
  '0,0|-1,2|0,-2': { note: 'families are important. so is disagreement - conflict is inevitable, and not always bad.', glyph: '🏡' },
  '0,0|-1,2|1,-2': { note: 'we’ve recently become rather soft. there’s plenty of grit left in us.', glyph: '🪨' },
  '0,0|-1,2|2,-2': { note: 'transparency beats privacy. i’d be happy for everything to be public.', glyph: '🔎' },
  '0,0|-1,2|2,-1': { note: 'harnessing energy is what defines humanity: fire, water wheels, steam, nuclear. we should be aiming to use more power per person, not less.', glyph: '⚡' },
  '0,0|-1,2|-2,0': { note: 'factory farming is probably the worst thing we currently do. i still eat meat. these are thoughts, not virtues.', glyph: '🥩' },
  // ---- the armchair, retired but not deleted (2026-07) ----
  // '-1,2': { section: true, glyph: '🛋', title: 'the armchair' },
  // '-1,2|1,0':  { note: 'thoughts from walks and the woodpile. positions stated, not defended. accuracy not guaranteed.', glyph: '🛋' },
  // '-1,2|0,1':  { note: 'i suspect pain and pleasure cancel out - the average of a wave is the middle. i haven’t worked out what to do about this, and it seems important.', glyph: '〰' },
  // '-1,2|-1,1': { note: 'i use ai all day and suspect the wave ends badly. fearing it and surfing it turn out to be compatible.', glyph: '🌊' },
  // '-1,2|-1,0': { note: 'we’re evolving minds the same way ours were evolved. if they end up feeling things, we’ll have made trillions of them. worth thinking about before, rather than after.', glyph: '🤖' },
  // '-1,2|0,-1': { note: 'small rules, unreasonable outcomes: evolution, economies, ant hills, most of my games. i keep pulling the same thread.', glyph: '🌱' },
  // '-1,2|1,-1': { note: 'animals are obviously conscious. one afternoon near a bellowing aurochs settles it; the rest is convenience.', glyph: '🐂' },
  // '-1,2|2,-1': { note: 'factory farming is the worst thing we currently do. i still eat meat. these are thoughts, not virtues.', glyph: '🥩' },
  // '-1,2|1,1': { section: true, glyph: '⚖', title: 'the ledger' },
  // '-1,2|1,1|1,0':  { note: 'does being alive net out? three doors, no exit.', glyph: '⚖' },
  // '-1,2|1,1|0,1':  { note: 'if consciousness is net zero, minds are just more weather. inconvenient, survivable.', glyph: '〰' },
  // '-1,2|1,1|-1,1': { note: 'if it’s net good, we should make as many minds as possible - a strange conclusion to hold politely at dinner.', glyph: '☀' },
  // '-1,2|1,1|-1,0': { note: 'if it’s net bad, a trillion instances would be the worst thing ever built. i’d rather we checked first.', glyph: '🌧' },
  // ---- easter eggs: unmarked cells in the procedural wilds. every
  // ancestor on each path is hash-verified deep, so a curious diver
  // can genuinely stumble onto them. no map. ----
  '-2,2|2,-2|0,1': { note: 'a wild cell. real bees build their comb in total darkness, measuring the 120° angles with their own bodies.', glyph: '🐝' },
  '-2,2|2,0|-2,0': { note: 'the closed end of a real honeycomb cell is three rhombi - half a rhombic dodecahedron. bees found the shape before we named it.',
                     glyph: '💠', href: '/games/polyhedra/', act: 'sculpt one' },
  '-2,0|-2,2|1,0': { note: 'a rubber duck. explain your problem to it. it has heard worse.', glyph: '🦆' },
  '0,0|0,2|2,-2': { note: 'the answer. you found it. now, what was the question?', glyph: '42' },
  '-1,-1|-1,1|1,-1': { note: 'one of the seven chickens. she gets everywhere. please don’t tell her about the others.', glyph: '🐔' },
  '-2,0|1,1|-1,2': { note: 'a tardigrade. it can survive vacuum, radiation, and being three levels deep in an imaginary honeycomb.', glyph: '🦠' },
  '0,-1|1,1|-1,0': { note: 'an easter egg. literally.', glyph: '🥚' },
  '-2,0|-2,2|-2,0|0,0|0,0': { note: 'five levels down. the honey is denser here. esc still works. probably.', glyph: '🕳' },
  '0,-1|2,0|0,2': { note: 'past websites: every earlier version of this site, embalmed. no map led you here.',
                    glyph: '🏛', href: '/museum/', act: 'visit' },
  '0,-1|-1,-1|-2,0|1,-2': { note: 'you are the first person to see this cell. statistically, that includes me.', glyph: '🔭' },
  '-2,2|-1,-1|0,-2': { note: '⬡', glyph: '' },
  '0,0|-1,2|-2,1': { note: 'seven chickens. the about room also says seven. it is the only number on this site i can personally guarantee.', glyph: '🐔' },
  '-2,2|-2,2|1,1': { note: '0 and 1 are the only real numbers.', glyph: '½' },
  '-2,2|-2,0|-2,0|-2,2|-2,1': { note: 'we only perceive the present, so in effect reincarnation is true. we have to endure. this cell is deep for a reason.', glyph: '🌒' },
  '-1,-1|0,-2|-1,2': { note: 'somewhere above you, a log is being split.', glyph: '🪓' },
};

// ---- the curated shelves; each fills its room via fillSection ----
const FILMS = [
  { glyph: '🎞', title: 'arrival', blurb: 'the safest bet i own. cried, in the end, at a grammar lesson.' },
  { glyph: '🎞', title: 'blade runner 2049', blurb: 'the philosophical-musings room, but with much better lighting.' },
  { glyph: '🎞', title: 'ex machina', blurb: 'my ai worries, dramatised, in ninety very tidy minutes.' },
  { glyph: '🎞', title: 'her', blurb: 'the same worry again, but sad and beige instead of frightened.' },
  { glyph: '🎞', title: 'ghost in the shell', blurb: 'the 1995 one. everything since has been quoting it, including me.' },
  { glyph: '🎞', title: 'the prestige', blurb: 'obsession, and a trick that actually pays off. i rewound the ending.' },
  { glyph: '🎞', title: 'memento', blurb: 'the structure is the whole magic trick. of course i love it.' },
  { glyph: '🎞', title: 'interstellar', blurb: 'divisive. i am precisely the person it was aimed at.' },
  { glyph: '🎞', title: 'children of men', blurb: 'the long takes quietly ruined every other film’s action for me.' },
  { glyph: '🎞', title: 'the road', blurb: 'see the bookshelf. i did this to myself twice, on purpose.' },
  { glyph: '🎞', title: 'mad max: fury road', blurb: 'two hours of craft, about one line of dialogue. perfect.' },
  { glyph: '🎞', title: '28 days later', blurb: 'the apocalypse, but british and faintly embarrassed. very wyndham.' },
  { glyph: '🎞', title: 'sicario', blurb: 'dread you can feel in your back teeth.' },
  { glyph: '🎞', title: 'pan’s labyrinth', blurb: 'a fairy tale with the safety off.' },
  { glyph: '🎞', title: 'no country for old men', blurb: 'not a wasted frame, not one sermon.' },
  { glyph: '🎞', title: 'annihilation', blurb: 'still not sure what i watched. i think that’s the point.' },
  { glyph: '🎞', title: 'spirited away', blurb: 'the ghibli one i’d save from a fire.' },
];

const BOOKS = [
  { glyph: '📕', title: 'john wyndham', blurb: 'the day of the triffids, the kraken wakes. the apocalypse, but polite and english.' },
  { glyph: '📕', title: 'the road', blurb: 'i think about it more than can be healthy.' },
  { glyph: '📕', title: 'the martian', blurb: 'competence as comfort reading.' },
  { glyph: '📕', title: 'world war z', blurb: 'the book. obviously the book.' },
  { glyph: '📕', title: 'the stand', blurb: 'very long. mostly earns it.' },
  { glyph: '📕', title: 'dune', blurb: 'filed in my notes with a question mark. the question mark is accurate.' },
  { glyph: '📕', title: 'brideshead revisited', blurb: 'the odd one out on this shelf. it stays.' },
  { glyph: '📕', title: 'harry potter', blurb: 'i was the right age and i regret nothing.' },
  { glyph: '📕', title: 'a song of ice and fire', blurb: 'from back when we all still believed.' },
  { glyph: '📕', title: 'battle mage', blurb: 'i will not be taking questions.' },
  { glyph: '📕', title: 'the dark tower', blurb: 'stephen king, all seven. i love the man; the stand most of all.' },
  { glyph: '📕', title: 'blood meridian', blurb: 'mccarthy with the gloves off. hard-core, and worth it.' },
  { glyph: '📕', title: 'project hail mary', blurb: 'more weir. read it in a weekend, then missed it.' },
  { glyph: '📕', title: 'the egg', act: 'read it', href: 'https://www.galactanet.com/oneoff/theegg_mod.html',
    blurb: 'andy weir, one page, free. i think about it on walks.' },
  { glyph: '📕', title: 'p.g. wodehouse', blurb: 'nothing at stake, everything in the sentences. the palate cleanser.' },
  { glyph: '📕', title: 'one flew over the cuckoo’s nest', blurb: 'kesey. the ending still turns up uninvited.' },
  { glyph: '📕', title: 'john le carré', blurb: 'spying as paperwork and quiet betrayal. no gadgets, all dread.' },
  { glyph: '📕', title: 'hamlet', blurb: 'shakespeare, yes, that one. annoyingly, it holds up.' },
];

const PLAYED = [
  { glyph: '🕹', title: 'the ones other people made', blurb: 'the games room next door is largely these games’ fault.' },
  { glyph: '🏭', title: 'factorio', blurb: 'the factory must grow. every automation game i’ve made since is this game’s fault specifically.' },
  { glyph: '⌛', title: 'braid', blurb: 'an all-time favourite. i have been chasing its kind of clever ever since.' },
  { glyph: '🗻', title: 'breath of the wild', blurb: 'i climbed everything. everything.' },
  { glyph: '🐑', title: 'baba is you', blurb: 'the rules are blocks you push. nothing has been quite the same since.' },
  { glyph: '🏝', title: 'the witness', blurb: 'line puzzles on an island of smug. loved it anyway.' },
  { glyph: '🔥', title: 'dark souls & elden ring', blurb: 'loved, despite the measurable cost to my health.' },
  { glyph: '⚫', title: 'go (baduk)', blurb: 'the only game here with no screen and no mercy.' },
  { glyph: '🌌', title: 'kotor', blurb: 'the twist got me completely. still not over it.' },
  { glyph: '🧙', title: 'divinity: original sin 2', blurb: 'co-op chaos with proper systems underneath.' },
  { glyph: '🐔', title: 'stardew valley', blurb: 'the chickens in it are considerably less trouble than mine.' },
  { glyph: '🍓', title: 'celeste', blurb: 'kind and merciless at once.' },
  { glyph: '🐛', title: 'hollow knight', blurb: 'wanted to love it. it declined.' },
  { glyph: '🔧', title: 'zachtronics games', blurb: 'admired from a respectful distance. i keep building my own versions with a rewind button, which is probably a review.' },
  { glyph: '💭', title: 'the pattern', blurb: 'logic, progression, automation. nothing that demands reflexes after nine pm.' },
];

// games will actually rates; the rest of games.json lands in the
// 'unfinished concepts' sub-room at the games room's centre cell
const DECENT_SLUGS = ['mirror', 'tile', 'shipshape', 'loom'];
const GAME_GLYPHS = { shipshape: '🚢', fathom: '🐙', lumen: '🏮', cascade: '🌊',
  fracture: '💥', recurr: '🌀', seed: '🌱', loom: '🧵', echo: '⏪', debt: '💸',
  drip: '💧', gridfire: '🔥', lanternwake: '🕯', mirror: '🪞', tile: '🔷' };
const PINNED_GAMES = [
  { glyph: '🏭', title: 'paint machine', act: 'play', href: '/games/paint-machine/', accent: '#ff9a3a',
    blurb: 'a little factory: emitters, colourers, portals, fans. build it, press play, watch it be wrong, rewind. 30 levels.' },
  { glyph: '📦', title: 'recursive sokoban', act: 'play', href: '/games/recursive-sokoban/',
    blurb: 'boxes contain whole levels. push one, step inside, solve it, climb back out.' },
  { glyph: 'λ', title: 'functional sokoban', act: 'play', href: '/games/functional-sokoban/',
    blurb: 'push value-boxes through function-boxes: +1, *2, NEG. then currying sneaks in. sorry.' },
  { glyph: '🪱', title: 'worm division', act: 'play', href: '/games/worm-division/',
    blurb: 'a worm that divides. then the copies start helping, which is somehow worse. it kept mutating.' },
  { glyph: '🟢', title: 'slime teleports', act: 'play', href: '/games/slime-teleports/',
    blurb: 'sokoban, except the slime teleports.' },
];
// featured at the top level of the comb, so not repeated in the games room
const FEATURED_SLUGS = ['recurr', 'drip'];
// first matching pattern names a post's glyph; ✍ is the fallback
const POST_GLYPHS = [
  [/vim/i, '⌨'], [/git/i, '🌿'], [/ruby|rails/i, '💎'], [/go module/i, '🐹'],
  [/shell|bash/i, '🐚'], [/audio/i, '🔊'], [/bsd|linux/i, '🐧'],
  [/ssh|gpg|sudo|root/i, '🔐'], [/aws|s3/i, '☁'], [/chatgpt|\bai\b/i, '🤖'],
  [/lisp|composition/i, 'λ'], [/twitter/i, '🐦'], [/cron/i, '⏰'],
  [/automat/i, '⚙'], [/sql|rows|table/i, '🗄'], [/\bjq\b/i, '🔧'],
  [/team|communicat|question|simplic|perfect|picture|enjoy|boring|document|defaults|done/i, '💭'],
];
