image: debian/buster
oauth: pages.sr.ht/PAGES:RW
packages:
  - pandoc
environment:
  site: wclarke.net
tasks:
  - install: |
      cd blog
      make install
  - build: |
      cd blog
      ./ssssg
  - package: |
      cd blog
      tar -C dst -cvz . > site.tar.gz
  - upload: |
      cd blog
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
      acurl -f https://pages.sr.ht/publish/will-clarke.srht.site -Fcontent=@site.tar.gz
