image: debian/stable
oauth: pages.sr.ht/PAGES:RW
packages:
  - pandoc
environment:
  site: wclarke.net
  GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
sources:
  - https://git.sr.ht/~will-clarke/wclarke.net
secrets:
  - de617511-6f48-4ec3-bf9c-a82dca64b85e
tasks:
  - install: |
      cd wclarke.net
      make install
  - build: |
      cd wclarke.net
      make build
  - package: |
      cd wclarke.net
      tar -C dst -cvz . > site.tar.gz
  - upload: |
      cd wclarke.net
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
      acurl -f https://pages.sr.ht/publish/will-clarke.srht.site -Fcontent=@site.tar.gz
