#!/bin/sh

debug=0

function md_files() {
    find src -type f | grep "\.md$" | sort -r
}

function main() {
    rm -rf dst
    rm -f src/index.md src/archive.md
    mkdir -p src dst/posts

    # generate an index.md from all our posts
    md_files | generate_index_md

    md_files | md_files_to_html_files

    cp -r src/css dst/css


    echo "Generated $(md_files | wc -l) files"
}

function md_files_to_html_files() {
    while read -r file_path
    do
        dst_path=$(src_to_dst_path "$file_path")
        if [ "$debug" == 1 ]; then
            echo $dst_path
        fi
        md_file_to_html_file "$file_path" > "$dst_path"
    done

}

function md_file_to_html_file() {
    input_file="$1"
    css_dir=$(realpath --relative-to="$input_file" "src/css/style.css")
    # echo css $css_dir

    pandoc \
        --data-dir dst \
        --css "./dst/$css_dir" \
        --include-before-body src/_top.html \
        --include-after-body src/_bottom.html \
        --title "Will Clarke" \
        --to=html5  \
        "$input_file"
        # --standalone \
    # --css=css/style.css
    #
        # --include-in-header=src/_header.html \
        # --css="$css_dir" \
}

function src_to_dst_path() {
    echo "$1" | sed -e's/src/dst/' -e's/\.md$/\.html/'
}

function generate_index_md() {
     echo "
---
title: Home
---
" >> src/index.md
    echo "
---
title: Archive
---
" >> src/archive.md
    while read -r file_path
    do
        md_file=$(cat "$file_path")
        title=$(echo "$md_file" | grep -iE '^title: ' | cut -d' ' -f 2-)
        description=$(echo "$md_file" | grep -iE '^description: ' | cut -d' ' -f 2-)
        date=$(echo "$md_file" | grep -iE '^date: ' | cut -d' ' -f 2-)
        tags=$(echo "$md_file" | grep -iE '^tags: ' | cut -d' ' -f 2-)

        dst_path=$(src_to_dst_path "$file_path" | sed 's#dst/##')
        formatted_date=$(gdate -d "$date" +"%e %B %Y")

        echo "
# [$title]($dst_path)
  $description ($formatted_date)
  $tags
" >> src/index.md
        echo "
- *"$date"* [$title]($dst_path)
" >> src/archive.md
    done
}

main
