#!/bin/sh

function main() {
    # some housekeeping...
    rm -rf dst tmp && mkdir -p src dst/{posts,tags} tmp/tags

    # generate index / archive / tag files from our posts
    find src/posts -type f | grep "\.md$" | sort -r | generate_tmp_md_files

    # find all markdown files and turn them into corresponding html in the dst path
    find src tmp -type f | grep "\.md$" | sort -r | \
        xargs -I {} sh -c 'md_file_to_html_file "{}" > "$(src_to_dst_path "{}")"'

    # md_file_to_html_file src/about.md > dst/about.html

    # create tags.html file
    find tmp/tags -type f | xargs -I {} basename {} ".md" | \
        xargs -I {} -n1 sh -c 'echo "- [{}](tags/{}.html) ($(wc -l < tmp/tags/{}.md | xargs))"' >> tmp/tags-unsorted.md
    sort tmp/tags-unsorted.md > tmp/tags.md
    md_file_to_html_file tmp/tags.md > dst/tags.html

    cp -r src/css dst/css

    echo "Generated $(find dst | wc -l) files"
}

function md_file_to_html_file() {
    input_file="$1"
    pandoc \
        --css="/css/style.css" \
        --include-before-body src/_top.html \
        --include-after-body src/_bottom.html \
        --title "Will Clarke" \
        --to=html5  \
        "$input_file"
}

function src_to_dst_path() {
    echo "$1" | sed -e's/src/dst/' -e 's/tmp/dst/' -e's/\.md$/\.html/'
}

function generate_tmp_md_files() {
    printf "Hello!👋😃\n\nI'm a software engineer based in the UK.\n\n---\n\n" > tmp/index.md
    while read -r file_path
    do
        md_file=$(cat "$file_path")
        title=$(echo "$md_file" | grep -iE '^title: ' | cut -d' ' -f 2-)
        description=$(echo "$md_file" | grep -iE '^description: ' | cut -d' ' -f 2-)
        date=$(echo "$md_file" | grep -iE '^date: ' | cut -d' ' -f 2-)
        tags=$(echo "$md_file" | grep -iE '^tags: ' | cut -d' ' -f 2-)

        dst_path=$(src_to_dst_path "$file_path" | sed 's#dst/##')
        formatted_date=$(gdate -d "$date" +"%e %B %Y")
        linked_tags=$(echo "$tags" | xargs -n1 -I {} echo "[{}](/tags/{}.html)")

        printf "# [$title]($dst_path)\n$description\n$linked_tags\n\n" >> tmp/index.md
        printf -- "- *"$date"* [$title]($dst_path)\n\n" >> tmp/archive.md
        echo "$tags" | xargs -n1 -I "{tag}" sh -c "echo \"- *[$title]($dst_path)* $date\" >> tmp/tags/{tag}.md"
    done
}

export -f md_file_to_html_file
export -f src_to_dst_path

main

# TODOs
# - tag headers on tag pages
# - rss feed
