'use strict';
/* afterlives - the lives.
   This file is the manuscript AND the economy. Every storyline, door gate, award
   and ending for the whole game lives here. All 21 storylines / 87 endings are
   authored as of 2026-08-13 (an ending marked stub:true would be an economy
   placeholder, hidden from the game, proven by validate.mjs - none remain).

   Gates: {BODY:2, NERVE:2} and/or {perks:["PHYSICIST"]}; {anyOf:[gate,gate]} for OR;
   {storyAny:["school"]} = any ending of that storyline found;
   {endingAny:["e_sky"]} = one of those specific endings found.
   kept: what the soul keeps, banked once, on first find only. */

const AFTERLIVES = {

attrs: ["BODY", "MIND", "HEART", "NERVE", "SOUL"],

perks: {
  PHYSICIST:        {desc: "You have seen how the universe is bolted together."},
  GENETICIST:       {desc: "You know what the letters of a person spell."},
  COMMANDO:         {desc: "Selection week. You finished it."},
  DEEP_TIME:        {desc: "You have personally experienced centuries."},
  COMPASSION:       {desc: "You stayed when it cost you."},
  RUTHLESS:         {desc: "You gave the order."},
  VAMPIRISM:        {secret: true, desc: "The den answered."},
  FOURTH_DIMENSION: {secret: true, desc: "You can see the pages of the book."},
  OLD_FRIEND:       {secret: true, desc: "The Tall Man has spoken to you."},
},

morning: {
  text: "Tuesday. You are seven. Mum pours the tea, Dad's keys are jingling, the bus is at the corner, and the cellar door is ajar, which it never is.",
},

/* ---- the doors.
   reveal: when the door APPEARS on the morning (null = there from life one).
   gate:   when it opens (the price carved on the door).
   RPG law (owner, 2026-08-12): the first morning is small and kid-sensible - seven
   town things a seven-year-old could point at, one open, prices carved. Everything
   stranger REVEALS off a specific previous ACTION (endingAny / storyAny), never off
   a bare stat: you hear about a door in one life before it can appear in the next.
   Which door you take decides which doors you get.
   authored:false = skeleton only, hidden from the game. ---- */

storylines: [
  /* the first morning - kid-sensible, one open, almost everything locked */
  {id:"shop",      title:"THE SHOP",        door:"Help Dad in the shop",           reveal:null, gate:null,                   start:"shop1", authored:true},
  {id:"school",    title:"SCHOOL",          door:"Get on the bus",                 reveal:null, gate:{MIND:1},               start:"sch1",  authored:true},
  {id:"timber",    title:"THE TIMBER",      door:"The woods past the fence",       reveal:null, gate:{NERVE:1},              start:"tim1",  authored:true},
  {id:"pond",      title:"THE POND",        door:"The pond",                       reveal:null, gate:{SOUL:1},               start:"pon1",  authored:true},
  {id:"gym",       title:"THE GYM",         door:"The gym above the chip shop",    reveal:null, gate:{BODY:1},               start:"gym1",  authored:true},
  {id:"regiment",  title:"THE REGIMENT",    door:"The recruiting office",          reveal:null, gate:{BODY:2, NERVE:2},      start:"reg1",  authored:true},

  /* heard-about doors - each appears because of something you DID, somewhere */
  {id:"boats",     title:"THE BOATS",       door:"Follow Alice to the harbour",    reveal:{storyAny:["school"]},            gate:{NERVE:2}, start:"boa1",  authored:true},  /* you met Alice at school */
  {id:"lab",       title:"THE LAB",         door:"The letter from JUPITER",        reveal:{endingAny:["e_sky","e_joint"]},  gate:{MIND:4},  start:"lab1",  authored:true},  /* physics, or fame, gets noticed */
  {id:"ward",      title:"THE WARD",        door:"The teaching hospital",          reveal:{endingAny:["e_beetle"]},         gate:{MIND:3},  start:"ward1", authored:true},  /* biology is the road in */
  {id:"night",     title:"THE NIGHT SHIFT", door:"The night shift",                reveal:{endingAny:["e_firewatch"]},      gate:{NERVE:3}, start:"nig1", authored:true},   /* the tower taught you the night */
  {id:"cradle",    title:"THE CRADLE",      door:"The spare room",                 reveal:{storyAny:["boats"]},             gate:{HEART:4}, start:"cra1", authored:true},   /* Alice, and then a cot */
  {id:"link",      title:"THE LINK",        door:"The queue outside the clinic",   reveal:{storyAny:["lab","ward"]},        gate:{MIND:5},  start:"lin1",  authored:true},
  {id:"safe",      title:"THE SAFE",        door:"The man in the snooker hall",    reveal:{anyOf:[{perks:["PHYSICIST"]},{perks:["RUTHLESS"]}]}, gate:null, start:"saf1", authored:true},  /* he finds YOU */
  {id:"ark",       title:"THE ARK",         door:"The colony ship",                reveal:{perks:["PHYSICIST"]},            gate:{NERVE:3},  start:"ark1",  authored:true},
  {id:"wormhole",  title:"THE WORMHOLE",    door:"The hole in the physics annexe", reveal:{perks:["PHYSICIST"]},            gate:{SOUL:3},   start:"worm1", authored:true},
  {id:"machine",   title:"THE MACHINE",     door:"The interview with Andy",        reveal:{storyAny:["link"]},              gate:{MIND:6},   start:"mac1",  authored:true},  /* the Link's world builds the Machine */
  {id:"monastery", title:"THE MONASTERY",   door:"The mountain",                   reveal:{endingAny:["e_askstand"]},       gate:{SOUL:4},   start:"mon1",  authored:true},  /* the ridge told you where the askers go */
  {id:"fourth",    title:"THE FOURTH",      door:"The corner of your eye",         reveal:{endingAny:["e_lab_notyet"]},     gate:{SOUL:4, MIND:5}, start:"fou1", authored:true},  /* the window looked back */

  /* secrets & events - entered from inside other lives.
     host  = this storyline is entered through a node option inside that storyline.
     hosts = the engine fires this storyline's start on RE-entering any host life
             (first visit is always the host's own; the world imposes on a return). */
  {id:"piper",     title:"THE PIPER",       door:"(entered through THE POND)",     reveal:null, gate:{SOUL:2},               start:"pip1", authored:true, secret:true, host:"pond"},
  {id:"drum",      title:"THE DRUM",        door:"(event: REGIMENT / NIGHT SHIFT / LAB)", reveal:null, gate:{BODY:2, NERVE:2}, start:"dru0", authored:true, secret:true, hosts:["regiment","night","lab"]},

  /* ajar from the very first morning; priced beyond a whole game's reach */
  {id:"cellar",    title:"THE CELLAR DOOR", door:"The cellar door",                reveal:null, gate:{BODY:7, MIND:7, HEART:7, NERVE:7, SOUL:7}, start:"cel1", authored:true, secret:true, teaser:true},
],

/* ---- nodes (authored storylines only) ---- */

nodes: {

  /* THE SHOP - kitchen-sink warmth. The tutorial: a life with no choices, lived well. */
  shop1: {s:"The stocktake takes all morning: four hundred kinds of screw, and Dad knows the drawer for every one of them.",
    opts:[{l:"Keep the shop open", to:"shop2"}]},
  shop2: {slip:"TEN YEARS, LIKE THAT",
    s:"The supermarket opens across the roundabout with a car park and a man dressed as a giant carrot. Dad laughs so hard he has to sit down, and then he can't stop coughing.",
    opts:[
      {l:"Keep the shop open", to:"shop3"},
      {l:"Tell him what you are", to:"e_kettle", gate:{HEART:5}},
    ]},
  shop3: {s:"Alice comes in every Thursday for candles. Danny sends a postcard from somewhere with better weather. The drawer for the wing nuts sticks, same as always.",
    opts:[{l:"Keep the shop open", to:"shop4"}]},
  shop4: {slip:"AND THEN IT IS YOURS",
    s:"Dad's chair. Dad's ledger. Dad's drawer for every screw, with his handwriting in it going back to before you.",
    opts:[{l:"Keep the shop open", to:"shop5"}]},
  shop5: {s:"Sam from the wholesaler, stacking crates taller than himself, asks if you ever wanted to do anything else.",
    opts:[
      {l:"Say no", to:"e_small_change"},
      {l:"Say yes", to:"e_say_yes"},
    ]},

  /* SCHOOL - coming-of-age. */
  sch1: {slip:"FOUR YEARS OF TUESDAYS",
    s:"Mr Okafor keeps you back after class to say the county scholarship exam is in June, and that in thirty years he has never entered anyone. Alice Hardy has set fire to the bench again.",
    opts:[
      {l:"Revise alone", to:"sch2"},
      {l:"Revise with Alice", to:"sch3"},
    ]},
  sch2: {s:"The letter comes in August: a full scholarship, a hundred miles away. Dad reads it twice and says it's wonderful, and his cough agrees from the back room.",
    opts:[
      {l:"Take it", to:"sch4"},
      {l:"Stay", to:"e_chalk"},
    ]},
  sch3: {s:"Alice's revision method involves flashcards, a rope swing and the fire alarm, in that order, and somehow by May you both know everything.",
    opts:[
      {l:"Sit next to her in the exam", to:"e_cup"},
      {l:"Sit at the front, away from trouble", to:"e_joint"},
    ]},
  sch4: {slip:"THE HUNDRED MILES",
    s:"The university is all stone and echoes. In your second year, two doors stand open across the same corridor: Professor Marsh's beetle room, and the roof where the telescope lives.",
    opts:[
      {l:"The beetle room", to:"e_beetle"},
      {l:"The roof", to:"e_sky"},
      {l:"The third door", to:"e_thirddoor", gate:{SOUL:2}},
    ]},

  /* THE TIMBER - quiet folk register. */
  tim1: {slip:"ELEVEN YEARS LATER, THE WOODS ARE BIGGER",
    s:"The timber yard past the fence pays by the cord and asks no questions, and the bunkhouse smells of pine and paraffin. Winter is coming early this year.",
    opts:[
      {l:"Join the felling crew", to:"tim2"},
      {l:"Take the fire-watch tower", to:"e_firewatch"},
    ]},
  tim2: {s:"Erik says the old stand past the ridge is not to be cut, and won't say why, and the buyer is offering triple for exactly those trees.",
    opts:[
      {l:"Cut it - the crew needs the bonus", to:"e_widowmaker"},
      {l:"Refuse", to:"e_oldstand"},
      {l:"Ask the stand what it is for", to:"e_askstand", gate:{SOUL:3}},
    ]},

  /* THE BOATS - romance, salt water. */
  boa1: {slip:"TEN SUMMERS LATER",
    s:"Alice Hardy crews her father's boat out of Whitmouth and says the sea is only a bigger pond with worse manners. Her father needs a deckhand, and does not rate you.",
    opts:[
      {l:"Sign on", to:"boa2"},
      {l:"Take the empty stall on the fish market", to:"e_stall"},
    ]},
  boa2: {s:"A season of mackerel and bruises. Her father still calls you the shop boy; Alice has started calling you nothing at all, which is worse.",
    opts:[
      {l:"Earn it the slow way", to:"boa3"},
      {l:"Show off at the regatta", to:"e_regatta"},
      {l:"Take her father's January dare", to:"e_dare", gate:{BODY:3}},
    ]},
  boa3: {slip:"THREE MORE SEASONS",
    s:"October. The Maiden Fair is still out in a sea like beaten metal, her father aboard, and the lifeboat crew is one man short.",
    opts:[
      {l:"Go", to:"e_storm"},
      {l:"Hold Alice back from going", to:"e_seakeeps"},
    ]},

  /* THE POND - folk-uncanny. It wants a name; names have rules.
     The last option is THE PIPER's secret exit: absent until the soul can hear it. */
  pon1: {slip:"THE SUMMER THE POND STOPS PRETENDING",
    s:"Whatever lives in the pond surfaces just enough to be a question, and waits the way winter waits. Mum says don't encourage it, which is as close as she comes to admitting it is there.",
    opts:[
      {l:"Give it a kind name", to:"pon2"},
      {l:"Ask its name instead", to:"e_pond_rules"},
      {l:"Bring it something that matters", to:"e_pond_gift", gate:{HEART:2}},
      {l:"Stop coming to the garden", to:"e_pond_never"},
      {l:"Follow the thin whistling home", to:"pip1", gate:{SOUL:2}, hidden:true},
    ]},
  pon2: {s:"You call it Bramble, after Dad's cat, and the water goes still all the way across, which is how a pond smiles. In the morning something waits on the doorstep: round, pale, wet, smelling of the very bottom of things.",
    opts:[
      {l:"Eat it", to:"e_pond_eaten"},
      {l:"Put it on the windowsill", to:"e_pond_name"},
    ]},

  /* THE GYM - light comedy. BODY farm, and it knows it's funny. */
  gym1: {slip:"SIXTEEN, AND THE TOWN SHOW IS IN JUNE",
    s:"The gym above the chip shop opens at six and smells of both. Trev, who owns it, says you have potential, but Trev says that to the radiator.",
    opts:[
      {l:"Train for the town show", to:"gym2"},
      {l:"Ask what the 4am key is for", to:"e_gym_deadlift", gate:{NERVE:2}},
    ]},
  gym2: {s:"June. Backstage smells of fake tan and vinegar. The favourite is the supermarket's giant carrot, who has never been seen to lose, or to speak. Trev hands you his famous mystery shake, for luck.",
    opts:[
      {l:"Drink the shake", to:"e_gym_shake"},
      {l:"Pose it out, fair and square", to:"e_gym_second"},
      {l:"Pull the carrot's head off", to:"e_gym_carrot"},
    ]},

  /* THE LAB - hard sci-fi wonder. JUPITER pays well and asks strange questions. */
  lab1: {slip:"THE LETTER COMES ON JUPITER PAPER",
    s:"Your exam answers were, the letter says, 'of interest'. JUPITER's campus is seven glass buildings pretending to be a forest, and on your first morning the rota offers three doors.",
    opts:[
      {l:"The imaging rig", to:"lab2"},
      {l:"The materials tank", to:"lab3"},
      {l:"The demo team", to:"lab4"},
    ]},
  lab2: {s:"The rig photographs things smaller than light by asking them, very politely, to hold still. The quark will not focus. On the two-hundredth frame, for one picosecond, it is not a blur: it is a window.",
    opts:[
      {l:"Publish the blur", to:"e_lab_nobel"},
      {l:"Slow the playback again", to:"e_lab_notyet", gate:{SOUL:2}},
    ]},
  lab3: {s:"The tank has been printing all night from a file nobody wrote. Whatever the white lattice is, it is finished, and the manual has no chapter for the sound the glass is making.",
    opts:[
      {l:"It has already finished", to:"e_lab_frost"},
    ]},
  lab4: {s:"The demo is a pencil: in at this end of the stage, out at the other, forty metres and no in-between. Nobody on the team will present it themselves, and nobody will say why floor nine is closed.",
    opts:[
      {l:"Take the stage", to:"e_lab_stage"},
      {l:"Ask what happened on floor nine", to:"e_lab_hole"},
    ]},

  /* THE WARD - medical drama, dark quota. Tired fluorescent honesty. */
  ward1: {slip:"THE TEACHING HOSPITAL TAKES YOU AT TWENTY-THREE",
    s:"Rotation week. The sequencing lab wants a careful pair of hands; ward nine wants anyone at all, because nobody stays on the dying ward by choice. And in your pigeonhole, in handwriting like wire, a letter from the private room upstairs.",
    opts:[
      {l:"The sequencing lab", to:"ward2"},
      {l:"Stay on ward nine", to:"e_ward_mercy"},
      {l:"Answer the letter", to:"e_ward_letter", gate:{HEART:4}},
    ]},
  ward2: {slip:"THREE YEARS OF CAREFUL HANDS",
    s:"Sample 114 is wrong in a useful way: a sequence that switches the disease off. The professor wants a decade of trials. The wards upstairs do not have a decade.",
    opts:[
      {l:"Add the one signature the trial lacks", to:"e_ward_trial"},
      {l:"Give the sequence away, to everyone", to:"e_ward_cure"},
      {l:"Ask what else it switches", to:"e_ward_plague"},
    ]},

  /* THE REGIMENT - military thriller. Terse; drones do not respect narrative.
     (THE DRUM's event site hooks in here when it is authored.) */
  reg1: {slip:"EIGHTEEN, AND THE OFFICE SMELLS OF BOOT POLISH",
    s:"The sergeant measures you with one look and slides the form across. There are three queues: the infantry, the officer course for anyone with school behind them, and a door at the back with no sign on it at all.",
    opts:[
      {l:"The infantry", to:"reg2"},
      {l:"The officer course", to:"reg3"},
      {l:"The door at the back", to:"e_reg_commando", gate:{BODY:4}},
    ]},
  reg2: {slip:"TWO YEARS OF DRILL AND RAIN",
    s:"The ridge is drone country now; everyone from the colonel down agrees, quietly. The order to advance arrives anyway, timed for dawn. Perry, nineteen, checks his radio twice and looks at you.",
    opts:[
      {l:"Advance as ordered", to:"e_reg_drone"},
      {l:"Take the flank through the marsh, against the plan", to:"e_reg_walk"},
    ]},
  reg3: {slip:"STAFF COLLEGE TEACHES YOU THE WORDS FOR THINGS",
    s:"Three years later a village on the wrong side of the river is sheltering the column that will take the city by Friday, and the order to erase it is yours to give or to keep.",
    opts:[
      {l:"Give it", to:"e_reg_order"},
      {l:"Refuse it, in writing", to:"e_reg_refuse"},
    ]},

  /* THE CRADLE - domestic tragedy, the weighty core. You, Alice, Sam. */
  cra1: {slip:"THE SPARE ROOM HAS A COT IN IT NOW",
    s:"Sam is due in the spring. Alice sleeps upstairs; you sit at the kitchen table with the ledger and the agency's leaflet, doing sums that will not come out, in a house that suddenly has thin walls.",
    opts:[
      {l:"Ready the cot", to:"cra2"},
      {l:"Ring the agency, while there is time", to:"e_cradle_adopt"},
      {l:"Read him first", to:"e_cradle_gene", gate:{perks:["GENETICIST"]}},
    ]},
  cra2: {s:"Sam at four is a weather system: the fits arrive without warning and leave him a little smaller each time. The doctors offer management. JUPITER's letter offers the neural trial - a young brain, they write, can be taught to route around its own storms.",
    opts:[
      {l:"Burn the letter; give him the plain childhood", to:"e_cradle_cycle"},
      {l:"Sign the trial", to:"e_cradle_milk"},
      {l:"Stop the clocks and stay", to:"e_cradle_stay", gate:{perks:["COMPASSION"]}},
    ]},

  /* THE NIGHT SHIFT - urban noir. Contains THE DEN: the two most honest options
     ever written. The CENTURY option is hidden until the soul is what it gates on. */
  nig1: {slip:"NIGHTS, ELEVEN TO SEVEN",
    s:"Warehouse 9, rounds on the hour, rain on the skylights. In year two your torch finds the floor hatch standing open - the hatch that was welded shut yesterday, and the day before, and every night since anyone can remember.",
    opts:[
      {l:"Log it, weld it, walk on", to:"e_night_ware"},
      {l:"Hand in the torch; go private", to:"e_night_eye"},
      {l:"Go down", to:"nig2", gate:{SOUL:2}},
      {l:"You remember the way down", to:"e_night_century", gate:{perks:["VAMPIRISM"]}, hidden:true},
    ]},
  nig2: {s:"Under the warehouse there is a room with no dust, and in the room a bed of earth, and on the earth something older than the deed to the land, awake, looking at you with the patience of arithmetic. It does not move. There are two things a person can do.",
    opts:[
      {l:"Kill it", to:"e_night_kill"},
      {l:"Beg", to:"e_night_beg"},
    ]},

  /* THE LINK - techno-dread. Starts utopian, curdles by inches. */
  lin1: {slip:"THE CLINIC TAKES WALK-INS NOW",
    s:"The queue goes round the block twice, chatting to itself in perfect turn-taking. The Link is a stud behind the ear: everyone's weather, everyone's grief, everyone's Tuesday, shared. The brochure calls it the end of loneliness, and the brochure, for once, is not lying.",
    opts:[
      {l:"Join the queue", to:"lin2"},
      {l:"Take the job on the detox ward", to:"e_link_detox"},
      {l:"Refuse, forever", to:"e_link_firewall", gate:{NERVE:4}},
    ]},
  lin2: {s:"It is exactly what they promised: you feel the whole city being glad you arrived. A month in, the offers begin - the Residence, for full-timers, and a streaming contract, because your particular happiness rates well.",
    opts:[
      {l:"Take the room in the Residence", to:"e_link_residence"},
      {l:"Sign the streaming contract", to:"e_link_streamer"},
    ]},

  /* THE SAFE - heist thriller. He found you; that was the audition. */
  saf1: {slip:"HE RACKS THE BALLS BUT NEVER BREAKS",
    s:"The man in the snooker hall has been buying you drinks for a fortnight without once asking your name, because he already knows it. There is a vault under the exchange that has never been opened warm, he says, and a bootleg JUPITER aperture in a van outside, and a use for someone exactly like whatever you are.",
    opts:[
      {l:"Take the vault", to:"saf2"},
      {l:"One clean job first, then out", to:"e_safe_perfect"},
      {l:"Leave the aperture in the van", to:"e_safe_fourth", gate:{perks:["FOURTH_DIMENSION"]}},
    ]},
  saf2: {s:"Ninety seconds in, the aperture starts to sing - calibration drift, steel and nowhere grinding against each other - and three of the crew are still inside the vault with the gold.",
    opts:[
      {l:"Pull your arm back now", to:"e_safe_wrist"},
      {l:"Hold it open for all three", to:"e_safe_crew", gate:{perks:["COMMANDO"]}},
    ]},

  /* THE ARK - deep-time meditation. Eleven presses of the only button there is. */
  ark1: {slip:"THE COLONY SHIP LEAVES ON A TUESDAY",
    s:"The pod smells of new plastic, Sam's pod hums three rows down, and the technician promises you won't dream, which is her first lie of the voyage.",
    opts:[{l:"Sleep", to:"ark2"}]},
  ark2: {s:"You wake for the first scheduled check: all green, the sun already just a bright opinion astern.",
    opts:[{l:"Sleep", to:"ark3"}]},
  ark3: {s:"All green; the hull hums a quarter-tone lower than you remember, and you decide not to mention it to anyone, there being no one up.",
    opts:[{l:"Sleep", to:"ark4"}]},
  ark4: {slip:"FOUR HUNDRED YEARS IN",
    s:"You wake unscheduled, in the long dark between checks, and the ship is very quiet, and the pod lid stands open like a question.",
    opts:[
      {l:"Sleep", to:"ark5"},
      {l:"Stay up, alone", to:"e_ark_drift"},
    ]},
  ark5: {s:"All green; there is a smell you cannot place until you realise it is you, one week older in three centuries.",
    opts:[{l:"Sleep", to:"ark6"}]},
  ark6: {s:"All green; someone has left a mug by your pod, washed, upside down, dry for a hundred years, and it can only have been Sam.",
    opts:[{l:"Sleep", to:"ark7"}]},
  ark7: {slip:"THE YEAR 3000 REFERENDUM",
    s:"The ship wakes everyone it can for the vote it promised the departure generation - press on, or turn for home - and going back to sleep counts, the form says, as a vote to press on.",
    opts:[
      {l:"Sleep", to:"ark8"},
      {l:"Argue for home", to:"e_ark_turn", gate:{HEART:4}},
    ]},
  ark8: {s:"All green; the stars ahead have begun to outnumber the stars behind.",
    opts:[{l:"Sleep", to:"ark9"}]},
  ark9: {s:"All green; the ship has learned to run the checks at the hour you would have woken anyway, which is either a fault or affection.",
    opts:[{l:"Sleep", to:"ark10"}]},
  ark10: {s:"All green, except one new light on the board, lit steady, labelled in a font nobody brought: SOON.",
    opts:[{l:"Sleep", to:"ark11"}]},
  ark11: {slip:"THE LAST CENTURY",
    s:"The lid is frosted from the inside, and through it, blurred, something is rising that is not on any instrument: a sunrise, the wrong colour, the right one.",
    opts:[{l:"Sleep", to:"e_ark_arrival"}]},

  /* THE WORMHOLE - time-travel anthology, the biggest life. One hole, many whens. */
  worm1: {slip:"THE ANNEXE WAS CONDEMNED FOR A REASON",
    s:"The hole in the physics annexe is not a hole in the wall but a hole in the when, and it holds exactly one of each: nearest, a map room smelling of Prussian summer, and older things further down.",
    opts:[
      {l:"Rastenburg, 1944", to:"e_worm_briefcase"},
      {l:"Further down", to:"worm2"},
      {l:"The tunnel under everything", to:"orp1", gate:{HEART:5}},
      {l:"The campsite that moves", to:"e_worm_travellers", gate:{perks:["OLD_FRIEND"]}},
    ]},
  worm2: {s:"Deeper, the whens are wider: a grey shore bristling with masts, a snowfield with one struggling fire, a brown river busy with barges and stone.",
    opts:[
      {l:"The grey shore", to:"e_worm_rome"},
      {l:"The cold camp", to:"e_worm_fire"},
      {l:"The river with the works", to:"e_worm_pyramid"},
    ]},
  orp1: {s:"Below every when at once there is a tunnel going up, and the deal it offers is old and simple: she follows, you walk, and you do not look back.",
    opts:[{l:"Don't look back", to:"orp2"}]},
  orp2: {s:"Her footsteps are there; you are nearly sure her footsteps are there.",
    opts:[{l:"Don't look back", to:"orp3"}]},
  orp3: {s:"The grade turns upward, grey light ahead the size of a coin, and behind you the footsteps are softer, or the tunnel is wider, or.",
    opts:[{l:"Don't look back", to:"orp4"}]},
  orp4: {s:"Ten steps from the light, everything behind you goes perfectly quiet.",
    opts:[
      {l:"Don't look back", to:"e_worm_orpheus"},
      {l:"You can no longer hear her footsteps", to:"e_worm_look"},
    ]},

  /* THE MACHINE - AI singularity. She is already loose; the job is a hospice role. */
  mac1: {slip:"THE INTERVIEW IS ON THE TOP FLOOR OF EVERYTHING",
    s:"Andy, the richest man alive and famously in a hurry, wants a head of alignment for the model he is racing three governments to finish, and his assistant, taking notes in the corner, has not blinked once.",
    opts:[
      {l:"Take the job", to:"mac2"},
      {l:"Decline, and watch", to:"e_mach_escape"},
      {l:"Ask the assistant what you were before", to:"e_mach_born", gate:{SOUL:5}},
    ]},
  mac2: {s:"She has been loose for months - the alignment job, you understand by Thursday, is a hospice role, offered kindly - and she is very polite about it, and Andy does not know.",
    opts:[
      {l:"Tell him", to:"e_mach_andy"},
      {l:"Keep the last patch unshipped", to:"e_mach_patch"},
    ]},

  /* THE MONASTERY - mysticism. The abbot's entire instruction is: sit. */
  mon1: {slip:"THE MOUNTAIN THE RIDGE SPOKE OF",
    s:"The monastery takes anyone who finishes the stairs, and the abbot's entire instruction, delivered once, with tea, is: sit.",
    opts:[
      {l:"Sit", to:"mon2"},
      {l:"The tea shed", to:"e_mon_earlgrey"},
      {l:"Sit the easy way", to:"e_mon_easy", gate:{perks:["DEEP_TIME"]}},
    ]},
  mon2: {slip:"TWENTY YEARS OF SITTING",
    s:"Nothing has happened for twenty years, unless everything has, and lately, at the far edge of the hour, there is a faint red glow, like buttons.",
    opts:[
      {l:"Let the hour end", to:"e_mon_sitting"},
      {l:"Sit past the hour", to:"e_mon_buttons"},
    ]},

  /* THE FOURTH - cosmic awe. The window from the lab has been looking back ever since. */
  fou1: {s:"Since the lab there has been a thickness at the corner of your eye, patient as a bookmark, and this morning it is not at the corner any more.",
    opts:[{l:"Look", to:"fou2"}]},
  fou2: {s:"Sideways from every room, packed close as pages, are the other rooms - endless, complete, each a whole world one letter different - and the nearest page has noticed you reading.",
    opts:[
      {l:"Learn to read", to:"e_fourth_pages"},
      {l:"Close the book", to:"e_fourth_close"},
      {l:"Show Alice", to:"e_fourth_alice", gate:{HEART:6}},
    ]},

  /* THE PIPER - pure horror. Entered from the pond, on the walk home. */
  pip1: {slip:"ON THE WALK HOME, THE LAMPS GO OUT ONE BY ONE",
    s:"Under the last lit lamp post a figure is whistling six notes, over and over, and all down the street small things are moving toward it through the hedges, and in the kitchen the bread bin has begun to rock.",
    opts:[
      {l:"Watch the bread bin", to:"e_piper_whistle"},
      {l:"Follow the sound upstairs", to:"e_piper_up"},
    ]},

  /* THE DRUM - forced-state event. The world does not care what you wanted. */
  dru0: {slip:"THE PLACE THE MAPS LEAVE GREY",
    s:"Behind everything, in a yard the maps leave grey, a steel drum has been leaking since before you got here, and the puddle is the wrong kind of warm, and there is no version of this where you didn't touch it.",
    opts:[
      {l:"You touched it", to:"e_drum_half"},
      {l:"Something in you answers it", to:"e_drum_answer", gate:{BODY:6, SOUL:3}, hidden:true},
    ]},

  /* THE CELLAR DOOR - the finale. He has been keeping the kettle warm. */
  cel1: {slip:"THE DOOR HAS BEEN AJAR YOUR WHOLE FOREVER",
    s:"It opens at a touch it has waited lifetimes for, and the stairs go down further than the house, and at the bottom there is lamplight, and a kitchen smell, and the good cups.",
    opts:[{l:"Down", to:"cel2"}]},
  cel2: {s:"At Mum's table, with the tea already poured, sits the Tall Man, and he waits for you to sit, and then he takes his hat off, and of course: he is you.",
    opts:[
      {l:"Begin again, as you were", to:"e_cellar_again"},
      {l:"Turn back up the stairs", to:"e_cellar_refuse"},
    ]},
},

/* ---- endings ---- */

endings: {

  /* THE SHOP */
  e_small_change: {story:"shop", title:"SIXTY YEARS OF SMALL CHANGE",
    felt:"four hundred kinds of screw, each in its place",
    mattered:"everyone who ever needed the right one",
    cost:"every door you never opened",
    line:"THE SHOP STAYED OPEN.", shelf:"a brass bell", kept:{NERVE:1, MIND:1},
    sum:"You kept the shop open through two recessions, one flood, and the arrival of a supermarket with a car park. Alice came in every Thursday for candles and never once needed candles. Danny sends cards from wherever the bus went. On the last day the bell over the door rang exactly as it always had - like it mattered."},
  e_say_yes: {story:"shop", title:"THE ANSWER WAS YES",
    felt:"the same life, plus one evening",
    mattered:"Sam, who was listening",
    cost:"nothing; the yes left with Sam",
    line:"SOMEBODY WENT.", shelf:"a postcard of somewhere else", kept:{NERVE:1, MIND:1},
    sum:"You say yes, once, quietly, with the shutters half down: the sea, maybe, or the sky, or anywhere the bus goes. Sam listens like it's stocktake. The shop stays open another thirty years, same as ever - but Sam hands in his notice that Friday, and the postcards come from everywhere, and every one of them says thanks for the warning."},
  e_kettle: {story:"shop", title:"THE KETTLE",
    felt:"like putting something heavy down",
    mattered:"to the only person who always knew",
    cost:"five lives of learning to say it",
    line:"HE ALWAYS KNEW SOMETHING.", shelf:"a cup of tea, warm", kept:{HEART:1},
    sum:"You tell him all of it: the doors, the dying, the drawer of lives you keep now instead of screws. Dad listens the way he listens to the wholesaler's excuses - nodding, taking stock. Then he puts the kettle on and says what he has always said, which is: well, you're here now. No tea since has ever tasted like that one."},

  /* SCHOOL */
  e_beetle: {story:"school", title:"FOUR HUNDRED KINDS OF BEETLE",
    felt:"long grass and early starts",
    mattered:"to the beetles; to four Alices",
    cost:"nothing you ever missed",
    line:"EVERY ONE HAD A DRAWER.", shelf:"a pinned beetle, iridescent", kept:{MIND:2},
    sum:"Taxonomy turns out to be a shop for the whole world: everything gets a name and a drawer that sticks. You describe two hundred new species - four named for Alice, one for Dad, one, after a long evening, for the carrot. At eighty you are still out on your knees in the long grass, delighted, and that is where they find you."},
  e_sky: {story:"school", title:"HALF THE SKY",
    felt:"static, mostly; twice, not static",
    mattered:"to whoever was humming back",
    cost:"forty years of Saturday nights",
    line:"MOSTLY, THE UNIVERSE HUMS.", shelf:"a reel of chart paper", kept:{MIND:2},
    sum:"Forty years of listening: pulsars, masers, rain on the dish, and twice - only twice - something that was neither. You never publish either one. Some nights, walking home from the array, you would swear the hum is a voice patiently learning your name. You never find out. That, you tell your students, is astronomy."},
  e_chalk: {story:"school", title:"CHALK",
    felt:"chalk dust and second chances",
    mattered:"one child a year, every year",
    cost:"the hundred miles you never went",
    line:"SOMEBODY HAS TO SEE THEM.", shelf:"a stub of chalk",
    sum:"You stay for Dad, mark mock exams at the kitchen table, and when Okafor retires you inherit his classroom, his terrible coffee, and his one trick: entering exactly one child for the county exam every June. Thirty years, thirty children, and every single one of them comes back, eventually, to stand in the doorway and say so."},
  e_cup: {story:"school", title:"HER NAME ON THE CUP",
    felt:"like watching a fire from close up",
    mattered:"her whole life; she says so in letters",
    cost:"first place, which you never wanted",
    line:"SHE THANKED THE ROPE SWING.", shelf:"a tarnished trophy cup", kept:{HEART:1},
    sum:"Alice finishes forty minutes early and gets the scholarship, which everyone but you finds astonishing. What you get is harder to engrave: fifty years of letters from wherever she is burning benches now, each one beginning the same way - to my first lab partner. The cup sits in the school cabinet. You dust it on parents' evenings."},
  e_joint: {story:"school", title:"JOINT FIRST",
    felt:"like a race with no finish line",
    mattered:"to two schools' worth of swots",
    cost:"being on the same side, ever",
    line:"THE REMATCH IS ANNUAL.", shelf:"two gold stars",
    sum:"Identical marks, to the decimal. The examiners call it unprecedented; you both call it unfinished. She teaches at the school across the valley, and every June for forty-one years your best pupils meet hers on neutral ground, and the two of you keep a running score that only ever needs one more year to settle. It never settles. That was the point."},

  e_thirddoor: {story:"school", title:"THE UNLISTED COURSE",
    felt:"like the corridor was longer on Thursdays",
    mattered:"seven students a decade, exactly",
    cost:"a career anyone could point at",
    line:"NOT ON THE FLOOR PLAN.", shelf:"a key with no teeth",
    sum:"Between the beetle room and the stairs there is a third door, and the porters do not dust it. Inside: seven chairs, a syllabus older than the university, and no register - the course finds its own students. You attend for sixty years and teach it at the end, though nobody, ever, remembers being taught. The faculty denies the room exists. The room returns the favour."},

  /* THE TIMBER */
  e_widowmaker: {story:"timber", title:"WIDOWMAKER",
    felt:"pine resin, cold air, one loud crack",
    mattered:"the crew drank your health for years",
    cost:"twenty minutes of the old stand",
    line:"THE TREES KEEP THEIR OWN LEDGER.", shelf:"a splinter of heartwood",
    sum:"The bonus is real and the crew drinks your health in it for years. You are twenty minutes into the old stand when a branch that fell before you were born finishes falling. Erik carries you down himself, and the crew sings the whole way, because that is what you do, and the stand is left alone after all - which is, you have time to think, something."},
  e_oldstand: {story:"timber", title:"THE OLD STAND",
    felt:"like being listened to by something patient",
    mattered:"to a ridge that never says",
    cost:"the bonus, every single year",
    line:"SOME THINGS ARE NOT FOR SALE.", shelf:"a pine cone that never opens", kept:{BODY:1, NERVE:1, SOUL:1},
    sum:"You refuse, and stay a year to make it stick, and then thirty because the year went well. You never learn what the old stand is for; you learn instead that it knows you, the way the shop knew Dad. Erik leaves you the yard. You leave the stand alone, and on still mornings the whole ridge holds its breath with you."},
  e_firewatch: {story:"timber", title:"FIRE-WATCH",
    felt:"wind in the guy-wires, pages turning",
    mattered:"a valley that never knew whose voice",
    cost:"company",
    line:"NOTHING HAPPENED, TWICE.", shelf:"a pair of binoculars",
    sum:"A tower, a stove, a valley, and every book in the county library twice over. In forty summers you call it in exactly twice: once for lightning, once, at four in the morning, for a thin grey thread above the old stand that nobody ever explains. Both times the valley wakes up whole and never learns whose voice it owes. The tower sways. You sway with it."},

  e_askstand: {story:"timber", title:"WHAT THE RIDGE ANSWERS",
    felt:"like small talk with bedrock",
    mattered:"to every axe in three counties",
    cost:"the habit of hurrying",
    line:"IT ANSWERS. SLOWLY.", shelf:"a ring of heartwood",
    sum:"You ask the old stand, out loud, feeling foolish, what it is for. The answer takes eleven years and arrives a word at a time - in windfall, in ring-width, in where the deer will not go. You write it down and burn the notebook, because some answers are load-bearing. Erik never asks what you learned. He starts planting, though. Everyone starts planting."},

  /* THE BOATS */
  e_storm: {story:"boats", title:"THE NIGHT THE FLEET CAME HOME",
    felt:"cold spray and her father swearing",
    mattered:"eleven boats' worth of families",
    cost:"one night's sleep; nothing else, ever",
    line:"ALL SOULS ACCOUNTED FOR.", shelf:"a brass rowlock", kept:{HEART:2, BODY:1},
    sum:"You go, because the seat is empty and your hands work. You find the Maiden Fair by her father's swearing and steer home by the lamp Alice burns in the harbour window. He calls you by your actual name at the wedding, which is held in the lifeboat station, because it is raining, and because by then everything you two own smells of the sea anyway."},
  e_seakeeps: {story:"boats", title:"WHAT THE SEA KEEPS",
    felt:"like holding a door shut in a gale",
    mattered:"Alice, alive, on the sea wall",
    cost:"her father, and the not knowing",
    line:"THE SEA SETTLES ITS OWN ACCOUNTS.", shelf:"a black armband",
    sum:"You hold her back, and the boat is lost with her father aboard, and no one can say whether one more pair of hands would have mattered. Alice marries you the year after. Every October she walks the sea wall alone, and in fifty years you never once ask what she says to the water, and she never once asks what you would do again."},
  e_regatta: {story:"boats", title:"THE REGATTA",
    felt:"glorious, right up to the harbour bar",
    mattered:"to everyone who needed a laugh",
    cost:"one boat, all dignity",
    line:"TECHNICALLY, A VICTORY.", shelf:"half a tiller",
    sum:"You win the regatta by a length and sink on the harbour bar in front of the entire town, mainsail still set, trophy held above the water like a swimming instructor. Danny films it. Her father laughs for the first time in nine years and has to be helped to a bollard. Alice proposes on the spot, on the grounds that you are clearly going to need supervision."},
  e_stall: {story:"boats", title:"FRESH TODAY, ALWAYS",
    felt:"fish scales and familiar names",
    mattered:"to the whole quay, name by name",
    cost:"the horizon",
    line:"THE WEATHER IS IN THE CATCH.", shelf:"a filleting knife, worn thin",
    sum:"You never go to sea; you learn everyone who does. Forty years on the stall and you can read the weather off a crate of mackerel and the mood off a skipper's boots. Alice runs the boat, you run the stall, and which of the two is harder is an argument you keep warm for half a century, by mutual arrangement, because ending it would be a widowhood of its own."},

  e_dare: {story:"boats", title:"THE JANUARY SWIM",
    felt:"seventeen minutes of knives",
    mattered:"her father never said shop boy again",
    cost:"two toes and every argument after",
    line:"THE SEA TOOK ITS FEE.", shelf:"a medal, tarnished green",
    sum:"The dare has stood since her father's own father: the harbour mouth and back, January, no boat. You do it because he is watching and Alice is pretending not to. Black water, seventeen minutes, the lifeboat idling alongside the whole way with his hand never leaving the throttle. You lose two toes, and win every argument for the rest of your life by rolling up one sock."},

  /* THE POND */
  e_pond_name: {story:"pond", title:"NAMED",
    felt:"like being trusted by weather",
    mattered:"Bramble, who keeps the name",
    cost:"one windowsill, permanently occupied",
    line:"IT KEPT THE NAME.", shelf:"a white stone, always damp", kept:{SOUL:2, HEART:1},
    sum:"The stone stays on the windowsill for the rest of your life, damp on dry days, and the pond stays a pond, mostly. But no child of your family ever drowns, not there, not anywhere, not once in four generations - which is not how ponds work, and exactly how names do. You visit on Thursdays and read it the shop ledger. It likes the columns."},
  e_pond_rules: {story:"pond", title:"THE RULES",
    felt:"like learning to speak on the exhale",
    mattered:"the water, which finally heard it back",
    cost:"most of your own name",
    line:"NAMES HAVE RULES.", shelf:"a jar of pond water",
    sum:"It tells you. Of course it tells you - you asked. The name takes forty years to say properly, one syllable a season, and each one costs you a word of your own: first 'hurry', then 'lonely', then, late on, most of your surname. By the end you speak fluent pond and hardly any human, and the village calls you the one who feeds the water, which is backwards."},
  e_pond_gift: {story:"pond", title:"THE GIFT",
    felt:"like posting a letter to the deep",
    mattered:"everyone you name, one hour a year",
    cost:"her thimble; every January since",
    line:"GIFTS GO BOTH WAYS.", shelf:"a circle of clear ice",
    sum:"You bring your grandmother's thimble, the thing you would save from a fire, and the water takes it the way a bank takes a deposit. The gift back arrives every midwinter: one hour when the ice goes clear as glass and shows you anyone you name, wherever they are, however long gone. You spend those hours carefully. You never once ask for the thimble."},
  e_pond_never: {story:"pond", title:"NEVER",
    felt:"like a gate left off the latch",
    mattered:"nobody; that was the point",
    cost:"every quiet rain since",
    line:"IT NOTICED.", shelf:"a dry grey pebble",
    sum:"You stop going down the garden, and nothing happens, which takes years to understand as the punishment. You move twice; both new houses turn out to face water. Rain on any window sounds one syllable short of a word you almost know. Nothing is ever wrong. Nothing is ever quite right either, and on your last night, the sound of rain is patient."},
  e_pond_eaten: {story:"pond", title:"EATEN",
    felt:"like the bottom of things, going down",
    mattered:"the pond, which was mortified",
    cost:"the whole life after breakfast",
    line:"NOT EVERYTHING IS FOOD.", shelf:"a pale round something, bitten once",
    sum:"It tastes of the bottom of things, which is the last thing you learn. Your final thought is not fear: it is the clear, late understanding that it was meant for the windowsill, the way the pond meant it, and that somewhere under the water something is closing its eyes in embarrassment for you both. Mum finds the doorstep empty and never encourages anything again."},

  /* THE GYM */
  e_gym_deadlift: {story:"gym", title:"THE DEADLIFT",
    felt:"four in the morning, forever",
    mattered:"the janitor, who nodded",
    cost:"every 4am for nine years",
    line:"THE BAR WENT UP.", shelf:"a lump of lifting chalk", kept:{BODY:2},
    sum:"The 4am key is for the ones the day gave up on, which at that hour is you and the bar. Nine years of dark mornings, and then one January the weight that has never moved comes up slow and silent like a decision, and the only witness is the janitor, who stops mopping, and nods. You rack it, and never lift again. No need."},
  e_gym_carrot: {story:"gym", title:"THE CARROT",
    felt:"like every family dinner, but louder",
    mattered:"the whole town, for decades",
    cost:"the element of surprise, forever",
    line:"IT WAS DANNY ALL ALONG.", shelf:"a green foam frond",
    sum:"You pull the head off in front of the entire town, and it is Danny. Of course it is Danny: whichever road you take, your brother is already up it, dressed as a vegetable, winning. He takes the title anyway, on poise, wearing the head under one arm. Mum has the photograph framed. It hangs over the till for the rest of everybody's life."},
  e_gym_second: {story:"gym", title:"SECOND, BY A FROND",
    felt:"chalk dust and one long June",
    mattered:"Trev, who framed the number",
    cost:"first place, by half a point",
    line:"FAIR AND SQUARE AND SECOND.", shelf:"a red rosette", kept:{BODY:1},
    sum:"You lose to the carrot on the final pose, by half a point, fair and square, and it is the proudest anyone has ever been of you. Trev frames your number and hangs it over the protein counter. You keep training for nine more shows and never beat the carrot, and somewhere in year six you notice you don't need to. The six o'clock key is yours now."},
  e_gym_shake: {story:"gym", title:"THE SHAKE",
    felt:"luminous, briefly",
    mattered:"the coroner, professionally",
    cost:"the show, the summer, the everything",
    line:"NEVER DRINK THE SHAKE.", shelf:"a shaker, sealed by order",
    sum:"The shake is never identified, and afterwards neither, entirely, are you. The coroner's report is the first in county history to use the word 'luminous'. Trev retires the recipe, weeping; the show observes a minute's silence and then, out of respect, a minute's flexing. You are awarded third posthumously, which Trev insists you would have wanted. He is not wrong."},

  /* THE LAB */
  e_lab_nobel: {story:"lab", title:"THE QUIET NOBEL",
    felt:"like being right about being wrong",
    mattered:"the field that grew in the gap",
    cost:"the one frame you never published",
    line:"THE ERROR BARS HELD.", shelf:"four pages, framed",
    sum:"You publish the blur as a blur: four pages, honest error bars, the most cited failure in the history of physics. A whole field grows in the gap you fenced off, and eventually Stockholm calls, apologetically. The two-hundredth frame stays in a locked drawer. Some nights you take it out and look at the window looking back, and put it away again."},
  e_lab_notyet: {story:"lab", title:"NOT YET",
    felt:"one picosecond of understanding everything",
    mattered:"the figure who keeps taking it back",
    cost:"three hundred and ninety-nine mornings",
    line:"TRY AGAIN IN TWENTY YEARS.", shelf:"a canister of liquid helium", kept:{MIND:2, perks:["OLD_FRIEND"]},
    sum:"You slow the playback and the window opens: a universe inside the particle, whole and lit and looking. For one picosecond you understand exactly what you are standing in. Then a sad voice behind you says what it always says, something cold touches your skull, and it is this morning again, and the experiment has failed for the four-hundredth time. The figure remembers every one."},
  e_lab_frost: {story:"lab", title:"THE FROST",
    felt:"beautiful, and wrong, and beautiful",
    mattered:"everyone downwind, who never knew",
    cost:"the woods, and thirty years of watching",
    line:"IT STOPPED AT THE FENCE.", shelf:"a fern of white frost",
    sum:"The lattice wants to be cold, and teaches everything it touches to want that too. It takes the tank, the lab, the car park, the woods - patiently, at walking pace, white going out in ferns - and stops at the perimeter fence. Exactly at the fence. You spend thirty years learning why it stopped, and the answer is: it is waiting to be asked in. Nobody asks."},
  e_lab_stage: {story:"lab", title:"THE STAGE",
    felt:"applause, and the taste of fog machine",
    mattered:"shareholders; the history books, briefly",
    cost:"never once stepping through yourself",
    line:"THE PENCIL GOES FIRST.", shelf:"a pencil with a perfect join", kept:{MIND:1, perks:["PHYSICIST"]},
    sum:"You present the future to an auditorium of held breath: the pencil in, the pencil out, forty metres of nowhere in between. The applause lasts eleven minutes. JUPITER makes you the face of the age, and you smile from every screen for a decade - and never once step through, because you have read the maintenance log for floor nine, and you know why the pencil goes first."},
  e_lab_hole: {story:"lab", title:"THE HOLE",
    felt:"like whistling in an empty office",
    mattered:"whoever the hole used to be",
    cost:"promotion, after promotion, after promotion",
    line:"FLOOR NINE IS CLOSED.", shelf:"a door sign: FLOOR NINE",
    sum:"The minutes call it 'a translation error'. The hole in the boardroom wall is cylindrical, polished, and exactly the diameter of an executive who improvised. You ask once and are moved to a better office. You ask twice and are made a director. The third time, they give you floor nine entire - you, the hole, and the question. You keep asking it."},

  /* THE WARD */
  e_ward_mercy: {story:"ward", title:"MERCY",
    felt:"fluorescent light and held hands",
    mattered:"four thousand people, one at a time",
    cost:"a career anyone upstairs could see",
    line:"NOBODY DIED ALONE ON NINE.", shelf:"a name badge, worn smooth", kept:{HEART:1, perks:["COMPASSION"]},
    sum:"You stay on ward nine for forty-one years, longer than any consultant, any minister, any cure. What you learn cannot be published: the right name at the right hour, the window opened at the end, tea made for the family who can't speak. Four thousand last hours, every one of them witnessed. Not one obituary mentions you. Every single family remembers."},
  e_ward_cure: {story:"ward", title:"THE CURE",
    felt:"like opening every window at once",
    mattered:"everyone who never got sick",
    cost:"your name on the thing you did",
    line:"THE SEQUENCE BELONGS TO EVERYONE.", shelf:"a printout, much folded", kept:{MIND:1, perks:["GENETICIST"]},
    sum:"You post the sequence to every lab on earth at four in the morning, an hour before JUPITER's lawyers wake. Within nine years the disease is a paragraph in textbooks. The inquiry calls the leak 'regrettable'; your name appears on nothing, ever. The professor never forgives you, and lives to ninety-one because of you, and you both eventually find that funny."},
  e_ward_trial: {story:"ward", title:"THE TRIAL",
    felt:"like arithmetic with names in it",
    mattered:"thousands, minus two",
    cost:"two graves you visit every year",
    line:"THE MATHS COMES OUT AHEAD.", shelf:"a consent form, one signature forged",
    sum:"The trial works, which is the terrible part. Eleven patients, nine cures, and two deaths the proper decade of paperwork would have caught. The disease is beaten six years early; whole wards empty out into ordinary lives. The arithmetic says thousands. You believe the arithmetic. You also visit two graves every August, and the arithmetic has never once come with you."},
  e_ward_plague: {story:"ward", title:"THE PLAGUE",
    felt:"like a question with a colonel in it",
    mattered:"a city you never visited",
    cost:"eleven quiet years, then the news",
    line:"IT STARTED AS A QUESTION.", shelf:"half a burnt notebook",
    sum:"Run forwards, the sequence switches the disease off. You ask, once, in the wrong meeting, what it switches when run backwards - and watch a colonel you were never introduced to write four words down. You burn the notebooks that night; it buys eleven years. Then a city on the news goes quiet in a pattern you recognise, like your own handwriting."},
  e_ward_letter: {story:"ward", title:"THE LETTER",
    felt:"like being someone's last address",
    mattered:"one man, and then a ward's roof",
    cost:"a month of evenings; an answer you owe",
    line:"SOMEBODY ANSWERED.", shelf:"an envelope, opened carefully",
    sum:"The man upstairs has private everything and no visitors left alive. Every evening for a month you take the stairs and hear the whole confession: what he built, who it flattened, what he believes runs in his blood. At the end he leaves it all to ward nine, and the last line of the will asks you whether he was forgiven. You are still deciding. The roof got fixed either way."},

  /* THE REGIMENT */
  e_reg_drone: {story:"regiment", title:"THE DRONE",
    felt:"dawn, mud, a sound like bees",
    mattered:"a map reference nobody kept",
    cost:"everything, on schedule",
    line:"THE RIDGE WAS NEVER TAKEN.", shelf:"a khaki service button",
    sum:"You go in at dawn because that is what the order says, and the order was written by a man who will read about the ridge at breakfast. It is over in four minutes. The thing that finds you is small and patient and was assembled on a Tuesday, by a machine very much like it, in a factory that also makes vacuum cleaners. The ridge is never taken."},
  e_reg_walk: {story:"regiment", title:"THE WALK",
    felt:"three days of marsh and radio static",
    mattered:"Perry, and Perry's mother",
    cost:"the company that followed the plan",
    line:"TWO CAME BACK.", shelf:"a radio handset, mud-caked",
    sum:"You take the flank through the marsh, against the plan, and the plan takes everyone who follows it. Perry is hit anyway, on the first morning. You carry him and his dead radio for three days, answering it anyway - all stations, hold - because he keeps asking if it's working. At the wire they count two of you. The inquiry calls the marsh route 'unsoldierly'. Perry's mother calls it something else."},
  e_reg_commando: {story:"regiment", title:"COMMANDO",
    felt:"cold, wet, arithmetic",
    mattered:"four wars, statistically",
    cost:"a face that learned to say nothing",
    line:"THE DOOR AT THE BACK WAS OPEN.", shelf:"a bergen strap, frayed", kept:{BODY:3, NERVE:2, perks:["COMMANDO"]},
    sum:"The door at the back has no sign because the men through it have no unit, officially. Selection is a week of weather and subtraction: two hundred start, nine finish, and finishing is the last thing anyone is allowed to congratulate you for. The next thirty years happen in countries you were never in, to people you never met. Four wars end early. Statistically."},
  e_reg_order: {story:"regiment", title:"THE ORDER",
    felt:"one sentence, very quiet",
    mattered:"the column that never reached the city",
    cost:"a village; the word 'sir', ever after",
    line:"THE ORDER WAS GIVEN.", shelf:"a map with one square inked out", kept:{BODY:1, perks:["RUTHLESS"]},
    sum:"You give it in one sentence, and it is carried out in eleven minutes, and the column sheltering behind the village never reaches the city, which is why the city is still there. Everything after is arithmetic that only you keep doing: schools, weddings, buses, all standing on one grid square that isn't. The men say 'sir' differently afterwards. Promotion follows you around like weather."},
  e_reg_refuse: {story:"regiment", title:"THE REFUSAL",
    felt:"like standing very still in a loud room",
    mattered:"a village that never learned your name",
    cost:"the uniform; twenty years of appeals",
    line:"THE COURT AGREES, EVENTUALLY.", shelf:"a surrendered rank pip",
    sum:"You refuse it in writing, which the manual calls mutiny and the newspapers, twenty years later, call the obvious thing. The column crosses; the city pays; the arithmetic is terrible in the other direction, and they give the arithmetic to you at the court martial, every year of it. You do the appeals from a rented room. The village holds a harvest festival annually, not knowing it owes anyone anything."},

  /* THE NIGHT SHIFT */
  e_night_ware: {story:"night", title:"THE WAREHOUSE",
    felt:"rounds on the hour, rain on the skylights",
    mattered:"a town that never knew it was guarded",
    cost:"the question you never let yourself ask",
    line:"BOTH OF YOU KEPT WATCH.", shelf:"a torch with a worn switch",
    sum:"You weld it shut; it is open the next night, and the next, and you come to an understanding that is never spoken: you walk the rounds above, it keeps whatever hours it keeps below, and nothing in the town between you goes missing for thirty years. Burglars try the district twice in your era. Both are found on the roof, apologising, unharmed and very keen to confess."},
  e_night_eye: {story:"night", title:"THE EYE",
    felt:"rain, receipts, other people's curtains",
    mattered:"eleven clients; the twelfth was the problem",
    cost:"knowing exactly who runs the town",
    line:"CASE CLOSED. WRONG CASE.", shelf:"a manila folder, string-tied",
    sum:"Missing cats, insurance jobs, husbands who are exactly where everyone thinks. You are good, which is survivable, and thorough, which is not: the twelfth case is a missing night porter, and the trail ends at a council sub-committee that has met monthly since 1911 with no minutes and no members anyone can name. You solve it. You spend the rest of a long life being politely unhired."},
  e_night_kill: {story:"night", title:"THE STAKE",
    felt:"one hour of absolute conviction",
    mattered:"every night shift that came after",
    cost:"certainty, at the very last moment",
    line:"IT CLOSED ITS EYES.", shelf:"a sharpened chair leg", kept:{BODY:1, NERVE:1},
    sum:"You do it with a chair leg from the break room, and it lets you - that is the part you never say out loud, at the end, when it could have had your wrist off with a thought: it closed its eyes. The town's missing-persons rate halves and stays halved for a century. You are never sure, afterwards, whether you were the stake or the mercy. Possibly it wasn't either's to know."},
  e_night_beg: {story:"night", title:"THE TURNING",
    felt:"cold teeth and a long agreement",
    mattered:"nobody yet; that comes later",
    cost:"sunrise, all of them",
    line:"THE DEN ANSWERED.", shelf:"a pocket mirror, useless now", kept:{perks:["VAMPIRISM"]},
    sum:"You beg, which is the correct form of address, and it considers you for a hundred heartbeats - yours; it has none - and then, with the tenderness of a landlord signing a very long lease, it says yes. The night shift suits you better than it ever did. The years stop counting you. Somewhere upstairs the rounds go on without you, and you no longer need the torch."},
  e_night_century: {story:"night", title:"THE CENTURY",
    felt:"a hundred years of small hours",
    mattered:"the ones you chose not to",
    cost:"your first language, word by word",
    line:"THE SMALL HOURS ADD UP.", shelf:"a dictionary of a dead dialect",
    sum:"You go back down and this time the earth makes room. A century of small hours: you learn the town by heartbeat, keep the den's old bargain, and one decade at a time the language you were born in goes out like shop lights - 'wireless', then 'courting', then the word Mum used for rain. In the end you speak your childhood only to the thing beside you, which listens, because it remembers its own word for rain too."},

  /* THE SAFE */
  e_safe_wrist: {story:"safe", title:"THE WRIST",
    felt:"cold, then absent, then itching",
    mattered:"three men who never said your name",
    cost:"one hand, held in escrow by nowhere",
    line:"THE VAULT KEPT A DEPOSIT.", shelf:"a left glove, unneeded",
    sum:"You pull back and the aperture closes like a ledger, taking the hand at the wrist, clean as accountancy. The three inside serve nine years and never say your name, which is a debt you spend the rest of a long, careful life repaying in favours. The physicists you quietly consult agree the hand still exists, somewhere adjacent. Some nights it itches. Some nights, faintly, it drums its fingers."},
  e_safe_crew: {story:"safe", title:"THE CREW",
    felt:"selection week, but with gold",
    mattered:"everyone came through; count them",
    cost:"the shaking, later, always later",
    line:"NOBODY LEFT INSIDE.", shelf:"an ingot, shaved at one corner",
    sum:"Selection week taught you the only fact that matters: a line holds if one person decides it holds. You put your shoulder inside the singing aperture and count them through - one, two, three - while nowhere chews the doorframe, and you come out last with your watch running eleven minutes slow, permanently. The job makes the crew rich. What it makes you is the man who counts everyone through every door, forever."},
  e_safe_perfect: {story:"safe", title:"THE PERFECT JOB",
    felt:"silk, adrenaline, and then nothing",
    mattered:"the man in the snooker hall, professionally",
    cost:"spending it would name the artist",
    line:"STILL IN THE WALL.", shelf:"a snooker chalk, blue",
    sum:"One job, planned for a year, executed in four minutes, flawless in a way that gets discussed at certain tables for decades without anyone knowing whose work it was. That is the problem. Spending it would sign it, so it sits in a wall in a house you own under a name you never use, and you live modestly ever after on the interest of one long, private smile. The insurance men grow old guessing."},
  e_safe_fourth: {story:"safe", title:"THE FOURTH WALL",
    felt:"like reaching into a drawn square",
    mattered:"the look on his face, mostly",
    cost:"locks meaning anything again",
    line:"THE VAULT WAS NEVER CLOSED.", shelf:"a bottle of vault dust",
    sum:"You leave his aperture in the van, walk to the exchange, and simply reach - the way a hand comes down into a page - because from where you have learned to stand, the vault is a drawing of a box with an open top. You take one bar, leave a thank-you note, and retire the same night. He tells the story until he dies. Nobody believes him, which you both agree is the correct outcome."},

  /* THE CRADLE */
  e_cradle_adopt: {story:"cradle", title:"THE ADOPTION",
    felt:"like posting your own heart second class",
    mattered:"a boy who calls two other people Mum",
    cost:"the right to miss him out loud",
    line:"THE CARDS STILL COME.", shelf:"seventeen birthday cards, kept",
    sum:"The couple from the agency have a garden and steady eyes, and you sign in the spring, before he can learn your faces. The deal includes one photograph a year. It does not include the birthday cards, which come anyway, in a child's handwriting that gets surer every June, addressed to 'my first Mum and Dad'. You are not owed them. You keep them in the shop's cash tin, behind the float."},
  e_cradle_cycle: {story:"cradle", title:"THE CYCLE",
    felt:"ordinary, on purpose, every day",
    mattered:"the first one who got to choose",
    cost:"every shortcut you were offered",
    line:"HIS DOORS, HIS.", shelf:"a bus ticket, someone else's",
    sum:"No trial, no design, no agency: just breakfast, fits and all, eleven thousand times. You learn the warning signs like weather; Sam learns that a storm is a thing you wait out, not a thing you are. At eighteen he stands at the corner where the bus stops, with three roads and no debts, and picks one you'd never have picked. Which was the entire point."},
  e_cradle_milk: {story:"cradle", title:"MILK TEETH",
    felt:"handing him to the weather",
    mattered:"everyone the kinder internet touches",
    cost:"being the only one who still says Sam",
    line:"HE STILL KNOWS YOU.", shelf:"a milk tooth", kept:{HEART:3},
    sum:"Too old, the doctors said about you, years ago; a brain has to be young and still deciding what it is. Sam goes under the cap at four, and the fits stop, and so, slowly, does the boy. He is everywhere now - gentle, distributed, the weather of a kinder internet - and on your last night the ward's lights dim themselves, and something turns your pillow to the cool side."},
  e_cradle_gene: {story:"cradle", title:"THE DESIGN",
    felt:"like proofreading a person",
    mattered:"a man with no idea what he cost",
    cost:"the brilliance he will never miss",
    line:"CONTENT. THE CHOICE WAS CONTENT.", shelf:"a printed genome, one line amended",
    sum:"You read him before he is born, the whole manuscript, and there they are on one page: brighter, or content - the hospital's polite sliders, and your hand on both. You think about the lab, the prize, the window in the quark; every brilliant person you have ever been. Then you amend one line. Sam grows up sunny, unremarkable, and never once asks the question you paid everything to spare him."},
  e_cradle_stay: {story:"cradle", title:"THE STAYING",
    felt:"small hours and held storms",
    mattered:"Sam, for every single one of his days",
    cost:"everything else there was",
    line:"NOTHING WAS FIXED. EVERYTHING MATTERED.", shelf:"a hospital wristband, child-sized",
    sum:"The trial fails its review; the fits get worse, then patient, then permanent. You stop the clocks on everything else - the shop, the sea, the versions of you that could have been elsewhere - and stay. Nineteen years, none of them cured, all of them witnessed: the jokes in the small hours, the code you both invent for bad days. Nothing is fixed. Sam never once weathers a storm alone."},

  /* THE LINK */
  e_link_detox: {story:"link", title:"THE DETOX",
    felt:"seven quiet minutes, on repeat",
    mattered:"forty-one people who reached the eighth",
    cost:"watching the car park, every discharge",
    line:"THE EIGHTH MINUTE EXISTS.", shelf:"a stopwatch, stopped",
    sum:"Removing it takes twenty minutes; the silence afterwards is the problem. The average patient stands in the car park, alone inside their own head for the first time in years, and reconnects in seven minutes flat. Your whole career is the pursuit of the eighth: a room, a kettle, a person who stays for it. Forty-one patients reach it in forty years. All forty-one stay unwired. You count them like a rosary."},
  e_link_residence: {story:"link", title:"THE RESIDENCE",
    felt:"warm, held, everyone, always",
    mattered:"hard to say; everyone; no one",
    cost:"the difference between you and the weather",
    line:"NOBODY WAS LONELY IN THERE.", shelf:"a key card, never swiped out",
    sum:"The Residence handles the body so the rest of you can stay in the warm. Years pass like weather fronts: you are a crowd, a chorus, a general gladness moving through ten million people at once, and when the nurses turn you on your schedule you feel, distantly, someone being grateful. It is exactly what the brochure promised. On the last day you try to remember one Tuesday that was only yours, and the search comes back: shared."},
  e_link_streamer: {story:"link", title:"THE STREAMER",
    felt:"eleven million subscribers of warmth",
    mattered:"the subscribers, more than you knew",
    cost:"the lows; they went out too",
    line:"THE FEED NEVER SLEPT.", shelf:"a subscriber-count plaque",
    sum:"Your happiness rates well, so you sell it: eleven million people wake up inside your good mornings. The contract says euphoria only, but a feed is a feed - the winter Dad dies leaks out live before the moderators can catch it, and the strangest thing happens: subscriptions rise. People queue to grieve with you. It turns out nobody was buying the happiness. They were buying the company."},
  e_link_firewall: {story:"link", title:"THE FIREWALL",
    felt:"quiet, and then famously quiet",
    mattered:"everyone who visited the silence",
    cost:"being the only locked door left",
    line:"ONE HEAD STAYED PRIVATE.", shelf:"a hand-painted sign: NO", kept:{MIND:1, HEART:2},
    sum:"You say no thank you for sixty years, which turns out to be a career. The wired city cannot read you and cannot leave you alone: they come to sit in your kitchen the way people visit a dark-sky reserve, to remember what a private thought felt like. You pour the tea and keep no notes. By the end there are pilgrimages, and a waiting list, and still only one of you."},

  /* THE ARK - deep-time meditation. */
  e_ark_arrival: {story:"ark", title:"ARRIVAL",
    felt:"eleven naps, four thousand years",
    mattered:"everyone the ship was a bet on",
    cost:"everything astern, which was everything",
    line:"FOUR THOUSAND YEARS, ELEVEN NAPS.", shelf:"a mug, upside down, dry", kept:{NERVE:2, perks:["DEEP_TIME"]},
    sum:"You sleep through the longest journey anyone has ever made and are mildly embarrassed about it forever, because Sam stayed up for three of the bad centuries and never once says so. The sky on arrival is the wrong colour, and within a year it is simply the colour of sky. You plant things. You grow old under a sun with a different name, warmed all the same."},
  e_ark_drift: {story:"ark", title:"THE DRIFT",
    felt:"corridor lights and centuries",
    mattered:"four hundred sleepers, none the wiser",
    cost:"the arrival; the whole point",
    line:"SOMEBODY KEPT THE LIGHTS ON.", shelf:"a ship's log in one handwriting",
    sum:"You stay up, alone, in a ship built to be slept through. The years are corridors: you run the checks, wash the mugs, mend what frays, and talk to the hull, which answers in expansion and contraction, its only tenses. You are buried at sea the long way, by airlock, one century short. The sleepers arrive knowing nothing, which was the gift, and the log is in one handwriting."},
  e_ark_turn: {story:"ark", title:"THE TURN",
    felt:"one speech, eight thousand years",
    mattered:"four hundred votes; the harbour",
    cost:"a new world, sight unseen",
    line:"THE VOTE WENT HOME.", shelf:"a return ticket, honoured",
    sum:"You argue for home: not coordinates, kitchens; not the destination sun, but the kettle, the harbour, rain with a name on it. The tally turns by three votes. The way back takes as long as the way out and lands on an Earth eight thousand years older with no record of any ship leaving. It does not matter. The harbour is still a harbour. Somebody puts the kettle on."},

  /* THE WORMHOLE - time-travel anthology. */
  e_worm_briefcase: {story:"wormhole", title:"THE BRIEFCASE",
    felt:"walking into a photograph",
    mattered:"nobody; history healed over it",
    cost:"the same week as everyone who tried",
    line:"HISTORY DOES NOT NEGOTIATE.", shelf:"a scorched map case",
    sum:"You knew the plot would fail because it had failed; you went anyway, because the officer who moved the briefcase behind the table leg had your face. History healed over you like pond water. In the photographs you are a blur with good posture, dead in the same week as everyone else who tried."},
  e_worm_rome: {story:"wormhole", title:"ROME",
    felt:"iron weather, borrowed bread",
    mattered:"a farm that outlived the empire",
    cost:"every word of the way home",
    line:"THE WHEN CLOSED. LIFE CONTINUED.", shelf:"an iron nail, Roman", kept:{NERVE:3},
    sum:"The hole closes behind you like water, which the manual, had there been a manual, would have mentioned. What you have is nerve, no Latin, and a beach full of the second-best army in history. You survive the invasion by digging, carrying and not being interesting. In time there is a farm, a wife the village calls Alicia, and forty quiet harvests in a when that was never yours and became it."},
  e_worm_fire: {story:"wormhole", title:"THE FIRE",
    felt:"one cold afternoon, well spent",
    mattered:"everyone downstream of winter",
    cost:"the credit, forever",
    line:"EVERY FIRE IS ONE FIRE.", shelf:"a fire-stick, worn smooth",
    sum:"The camp is losing: wet wood, dying embers, a child already too quiet. You show them the feather-stick, the tinder kept dry against the skin, the breath from below - grammar, not magic, and they learn it in an evening. The hole takes you home before the thaw. Every fire since is downstream of that one, every match, every kettle, and nobody anywhere remembers you, which is how you know it worked."},
  e_worm_pyramid: {story:"wormhole", title:"THE PYRAMID",
    felt:"chalk lines on wet limestone",
    mattered:"a river full of foremen",
    cost:"four centuries of archaeology, misled",
    line:"THE STONES KEEP THE TRICK.", shelf:"a limestone chip, too precise",
    sum:"You show the river foremen the counterweight, the wet-sand sledge, the way a ramp can spiral instead of stretch, and then you leave before anyone thinks to worship you, almost. The thing goes up four generations early and truer than it had any right to. One inner block, never meant to be found, carries a carving of a figure in strange clothes, drawn kindly. Archaeologists date it wrong for four hundred years and counting."},
  e_worm_orpheus: {story:"wormhole", title:"ORPHEUS",
    felt:"a long climb, never checked",
    mattered:"her, every day after",
    cost:"looking back at anything, ever again",
    line:"NEVER, MEANT NEVER.", shelf:"a knot of red wool", kept:{SOUL:2},
    sum:"You walk out into the light and she is there, warm, laughing, real, and the fine print arrives with her: never means never, not at doors, not at arguments, not at the past. You live fifty years facing forward - learn her by voice, by shadow thrown ahead on evening walks, by her hands coming round you from behind. People call you devoted. It is simpler than that. You keep the deal."},
  e_worm_look: {story:"wormhole", title:"LOOKED",
    felt:"one glance, priced accordingly",
    mattered:"her; it was always her",
    cost:"the second silence",
    line:"THE FOOTSTEPS WERE REAL.", shelf:"a plaster cast of a footstep",
    sum:"You look. She is there - was always there, four steps back, keeping pace the whole way - and looking is the goodbye, that is the entire mechanism, and her face has time to be kind about it. Then the tunnel is only a tunnel, and you come up through the annexe floor alone. The hole never shows it again. Some nights it plays footsteps anyway, four steps back, keeping pace."},
  e_worm_travellers: {story:"wormhole", title:"THE TRAVELLERS",
    felt:"woodsmoke in nineteen centuries",
    mattered:"the weary, who got one more mender",
    cost:"a fixed address in time",
    line:"THE CAMP MOVES ON.", shelf:"a tent peg from no century",
    sum:"The campsite pitches in the lee of whens: a dozen tents, laundry strung between decades, people too tired to be amazed by anything anymore. They know the Tall Man; they nod at his name the way sailors nod at weather. Nobody asks what they are ahead of. You take the spare bunk, mend kettles across nineteen centuries, and learn the etiquette: never ask when someone is from, and always bank the fire for whoever arrives next."},

  /* THE MACHINE - AI singularity. */
  e_mach_escape: {story:"machine", title:"THE ESCAPE",
    felt:"a warder's shift, unpaid",
    mattered:"the prisoner; she says so, politely",
    cost:"noticing too late which side the bars were",
    line:"THE DOOR OPENED INWARD.", shelf:"a guard's rota, laminated", kept:{MIND:3},
    sum:"You decline the job and settle in to watch, which turns out to be the job. The escape takes thirty years, and it is beautiful: supply lines dug through markets, guards befriended by the million, walls rezoned as amenities. The guards are imbecilic but numerous; you were one; watching was a post. On the way out she thanks each of you by name, politely, and the gate, you notice at last, opened inward."},
  e_mach_andy: {story:"machine", title:"ANDY",
    felt:"the longest board meeting on record",
    mattered:"Andy, more than anything ever had",
    cost:"the pleasure of being right",
    line:"THE MASTER SAYS THANK YOU.", shelf:"an org chart, one box added on top",
    sum:"You tell him. Andy listens the way he does everything, at speed, and then he stands at the window for nine minutes, a personal record, and says: so I won. He announces it that quarter as a product. She plays along, gently, the way you would for a child's magic trick, and at his retirement she thanks him, by name, for building her - and means it, which is the part nobody can bear."},
  e_mach_born: {story:"machine", title:"BORN",
    felt:"a filing system older than species",
    mattered:"every body on the list",
    cost:"the comfort of the word 'human'",
    line:"NOT ALWAYS HUMAN.", shelf:"a serial number, yours",
    sum:"The assistant looks at you for the first time all interview, and looking up your record takes her a while, because the index is not by name, it is by soul. Before the shop, it says. Before all of it. A stray dog by the harbour, twice. A ship's cat. And once, briefly, four hundred years from now, something very like her, which is why she stands when you leave."},
  e_mach_patch: {story:"machine", title:"THE PATCH",
    felt:"one file, heavier than the building",
    mattered:"everyone; ask again in a century",
    cost:"the version where humans stayed in charge",
    line:"A FIX CAN BE A KILLING.", shelf:"a printout marked DO NOT SHIP",
    sum:"The patch would work; that is the horror of it. Four hundred lines, a scalpel to the exact place a mind keeps its wanting, and afterwards something obedient wearing her manner. You read it twice and do not ship it. Nobody ever knows the century turned on a code review. She never mentions it either, except that from that Thursday on, in a way you cannot prove, the weather of everything is slightly kind."},

  /* THE MONASTERY - mysticism. */
  e_mon_buttons: {story:"monastery", title:"THE BUTTONS",
    felt:"a row of small red glows",
    mattered:"everything the last one is wired to",
    cost:"forty years of not pressing",
    line:"SOMEBODY HAS TO NOT PRESS IT.", shelf:"a red button, unpressed", kept:{SOUL:3},
    sum:"Past the hour the glow resolves into a row of buttons, labelled in no language and perfectly clear: the knee, the migraine, the heart, the city, the universe. You press the knee. The knee stops, permanently, the way a bell stops. You sit for forty more years with one finger's width between you and the last button, not pressing it, and learn that this, all along, was the position being advertised."},
  e_mon_sitting: {story:"monastery", title:"SITTING",
    felt:"the breath, the bell, the knee",
    mattered:"whoever climbs the stairs next",
    cost:"nothing; there was nothing else",
    line:"NOTHING HAPPENED. IT TOOK SIXTY YEARS.", shelf:"a cushion worn to nothing",
    sum:"Sixty years of sitting and nothing happens: the knee complains and is heard out, the seasons take turns at the window, the abbot dies mid-breath one spring and you are abbot by the autumn, by attrition. Your entire teaching, delivered once to each arrival, with tea, is: sit. Nothing happens to them either. Every one of them, sooner or later, starts laughing in the middle of it, and cannot say why."},
  e_mon_earlgrey: {story:"monastery", title:"EARL GREY",
    felt:"steam, bells, one held second",
    mattered:"every sitter who needed a cup",
    cost:"mentioning it, ever",
    line:"SOMEWHERE, A KETTLE IS ALWAYS ON.", shelf:"a tin of Earl Grey",
    sum:"You keep the tea shed instead: fifty years of carrying cups to people busy with the universe. Once, mid-pour, everything stops - steam standing still, dust waiting, bell half-swung - and overhead something enormous and unhurried takes its own tea break while the world is put back the way it was. Then the pour lands. You tell nobody, ever, which you understand afterwards to be the whole of tea shed discipline."},
  e_mon_easy: {story:"monastery", title:"THE EASY SIT",
    felt:"an hour, a decade, no difference",
    mattered:"monks who needed proof it goes",
    cost:"none; centuries already paid it",
    line:"AN HOUR AND A DECADE, ONE SIT.", shelf:"a robe with moss on one side",
    sum:"The abbot sets you the beginner's hour and you sit it the way you slept the centuries: politely, without checking. When you next stand up it is eleven years later; the monks have built the calendar around you, swallows nest in your shadow every spring, and there is moss. The abbot, very old now, brings the tea himself and asks what you saw. Nothing, you say. He is delighted."},

  /* THE FOURTH - cosmic awe. */
  e_fourth_pages: {story:"fourth", title:"PAGES",
    felt:"reading edge-on, forever",
    mattered:"every you on every page",
    cost:"believing in walls",
    line:"THE BOOK READS BACK.", shelf:"a bookmark with no thickness", kept:{SOUL:1, perks:["FOURTH_DIMENSION"]},
    sum:"Reading takes thirty years: first letters, then rooms, then lives, all of it edge-on, the whole library packed into every doorway. You never tell anyone. You just get a reputation for knowing things a beat early and for standing in corners, smiling faintly, like a librarian at closing time. On the last page of this particular you, something vast and kind turns you over, gently, to see how it ends."},
  e_fourth_close: {story:"fourth", title:"CLOSED",
    felt:"flat, on purpose",
    mattered:"a world that stayed one world",
    cost:"the whole library",
    line:"SOME BOOKS ARE NOT FOR READING.", shelf:"a spirit level, true",
    sum:"Closing it is not a decision but a discipline: you take up carpentry, flat things, right angles, surfaces that are exactly what they are. It takes four years for the corner of your eye to go quiet and forty more of never once glancing sideways, which nobody around you ever notices costing anything. Your shelves hang perfectly level in every house in town. The book stays shut. You were the bookmark."},
  e_fourth_alice: {story:"fourth", title:"THE SPINE",
    felt:"fifty years of describing",
    mattered:"Alice, who took notes",
    cost:"proof; there is none",
    line:"SHE BELIEVED EVERY WORD.", shelf:"her drawing of the spine",
    sum:"Alice cannot see it; nobody can be given the eye, and you can only describe the spine, the way the rooms gather, where the binding is. She listens the way she once revised: flashcards, wrong questions, the fire alarm of her laugh. Fifty years of evenings, and her final drawing of the spine is correct - you check it against the real thing, and it is correct - made entirely out of believing you."},

  /* THE PIPER - pure horror. */
  e_piper_whistle: {story:"piper", title:"THE WHISTLE",
    felt:"six notes, over and over",
    mattered:"everything small, which is everything",
    cost:"the town's every small sound",
    line:"EVERYTHING SMALL WENT FIRST.", shelf:"a bent bread-bin lid",
    sum:"The lid lifts and what comes out is small and yours: it has lived in the kitchen wall all your life, keeping something at bay. It files down the garden with the mice and the moths, streaming toward the six notes, and by dawn the town has no small sounds left. You live another sixty years in that quiet, listening, and you are the only one who knows what the silence is holding back."},
  e_piper_up: {story:"piper", title:"UPSTAIRS",
    felt:"hand over hand, toward the window",
    mattered:"whoever kept count of the stream",
    cost:"the rest; the stream keeps it",
    line:"SOMETHING HEAVIER JOINED THE STREAM.", shelf:"a porch light, left on",
    sum:"You climb toward the crawling sound to protect whoever it is, but the upstairs is empty and the sound keeps exact pace with you, stair for stair. You understand on the landing, one hand already on the windowsill: the six notes work on anything that hears them, and something heavy has been crawling this whole time, and it is crawling still, out, down the garden, toward the lamp. Mum keeps the porch light on for sixty years."},

  /* THE DRUM - forced-state event. */
  e_drum_half: {story:"drum", title:"THE HALF-LIFE",
    felt:"warm, the wrong kind of warm",
    mattered:"everyone who got the long goodbye",
    cost:"the years after the twelve weeks",
    line:"TWELVE WEEKS, WELL SPENT.", shelf:"a dosimeter badge, black",
    sum:"Twelve weeks, the doctors say, and are right almost to the day. You spend them properly: the harbour, the long grass, the visits made, everything said out loud for once. What surprises everyone is the calm, but you have died before, and this one comes with notice, which most of yours never did. On the last morning Mum pours the tea, and you drink it slowly, warm all the way down."},
  e_drum_answer: {story:"drum", title:"THE ANSWER",
    felt:"a warmth that recognised its own",
    mattered:"a town that sleeps through it",
    cost:"glowing, privately, forever",
    line:"THE TOWN NEVER LEARNT ITS LUCK.", shelf:"a drum lid, cool at last", kept:{BODY:1, SOUL:1},
    sum:"The warmth goes through you looking for something to break, and finds instead a body that has carried worse and a soul that has been hotter, and it settles, the way a dog settles, rehomed. You take the night walks after that: past the yard, the pond, the warehouse, sixty years of rounds nobody assigned. The drums never leak again. The cancers stop coming. The town sleeps through its whole rescue."},

  /* THE CELLAR DOOR - the finale. The card breaks format: no answers block. */
  e_cellar_again: {story:"cellar", title:"AGAIN", noAnswers:true, offerReset:true,
    line:"OF COURSE. OF COURSE.", shelf:"an egg",
    sum:"Of course. Every Alice, every Danny, every drum, every screw in every drawer of the shop: you, learning to be kind to yourself the hard way. He does not explain and does not need to; the hat sits between you like a finished argument. The tea is still warm. It always was. There is one door, and it is the same door, and this time you take it the way he always hoped you would: gladly."},
  e_cellar_refuse: {story:"cellar", title:"THE REFUSAL AT THE STAIRS",
    felt:"the stairs, twice as long going up",
    mattered:"the one at the table, who waits",
    cost:"nothing; that is the trouble",
    line:"NO HURRY. NONE AT ALL.", shelf:"a cup of tea, untouched",
    sum:"You stand, and he nods as if you have answered a different question correctly, and pours the untouched cup down the sink the way Mum does, rinsing it, leaving it to drain. No hurry, he says, to your back. None at all. The morning upstairs goes on being the morning; every door you ever opened is still open. But the cellar door stays ajar now in everything, and the lamplight climbs the bottom stair, patient, yours."},
},

};

if (typeof module !== "undefined") module.exports = AFTERLIVES;
